slices/libc6.yaml, slices/libcom-err2.yaml, slices/libcrypt1.yaml, slices/libgcc-s1.yaml, slices/libgssapi-krb5-2.yaml, slices/libicu70.yaml, slices/libk5crypto3.yaml, slices/libkeyutils1.yaml, slices/libkrb5-3.yaml, slices/libkrb5support0.yaml, slices/libssl3.yaml, slices/libstdc++6.yaml, slices/zlib1g.yaml
Tested with chisel with commits from PR
https://github.com/canonical/chisel/pull/12 applied:
slices="base-files_base libc6_libs libgcc-s1_libs libssl3_libs libstdc++6_libs zlib1g_libs ca-certificates_data"
for a in amd64 arm64 armhf i386 ppc64el riscv64 s390x; do
mkdir output-$a
chisel cut --release ~/devel/chisel-releases/ --root $PWD/output-$a --arch $a $slices
done
=> Select arch-specific paths by globs

slices/aspnetcore-runtime-6.0.yaml, slices/dotnet-host.yaml, slices/dotnet-hostfxr-6.0.yaml, slices/dotnet-runtime-6.0.yaml, slices/liblttng-ust-common1.yaml, slices/liblttng-ust-ctl5.yaml, slices/liblttng-ust1.yaml, slices/libnuma1.yaml, slices/libunwind-13.yaml
dotnet6 is currently in kinetic, but not yet in jammy. Add dotnet6 slices to
ubuntu-22.10 branch.
PLEASE DO NOT squash merge this PR. The commit that adds dotnet6 shall be
cherry-picked to ubuntu-22.04 branch once dotnet6 packages hit jammy archive.
=> Add dotnet6 to new 22.10 (kinetic) branch

slices/aspnetcore-runtime-6.0.yaml, slices/dotnet-host.yaml, slices/dotnet-hostfxr-6.0.yaml, slices/dotnet-runtime-6.0.yaml, slices/liblttng-ust-common1.yaml, slices/liblttng-ust-ctl5.yaml, slices/liblttng-ust1.yaml, slices/liblzma5.yaml, slices/libnuma1.yaml, slices/libunwind-13.yaml, slices/libunwind8.yaml
The .NET packages are now in `jammy-updates`, so this PR includes the SDFs (very similar to the ones in `ubuntu-22.10`'s chisel release) for the .NET family (ASP.NET included) and all their dependencies.
Tested with a modified version of Chisel capable of fetching from `<animal>-security` and `<animal>-updates`.
=> add .NET slice definition files and dependencies

chisel.yaml
`suites` are now supported: https://github.com/canonical/chisel/commit/eeba4447c62e328cf69385ad60674892b4d25414#diff-99ed201a7fb88dfcb98a03a2e56645e2f71d8124cdee8b818df454ee12dcaa57
=> define jammy suites in chisel.yaml

chisel.yaml
add the security and updates suites to 22.10
This was motivated by the recent release of OpenSSL, which has fixed a critical vulnerability affecting Jammy and Kinetic.
=> feat: add security and updates suites to 22.10

slices/base-files.yaml
Same as in https://github.com/canonical/chisel-releases/pull/14, but for Kinetic
=> [22.10] add release-info slice to base-files slice definition file

slices/dotnet-host.yaml, slices/dotnet-hostfxr-6.0.yaml, slices/dotnet-runtime-6.0.yaml
(same as https://github.com/canonical/chisel-releases/pull/23, but for Kinetic)
=> fix: dotnet* pkgs new content structure (22.10)

slices/dotnet-host.yaml, slices/dotnet-hostfxr-6.0.yaml, slices/dotnet-runtime-6.0.yaml
At the moment, due to an update of the .NET debs, Chisel will complain about:
```bash
$ chisel cut --root output dotnet-runtime-6.0_libs
(...)
2022/11/29 08:52:27 Extracting files from package "dotnet-host"...
error: cannot extract from package "dotnet-host": no content at /usr/lib/dotnet/dotnet6-*/dotnet
```
After the upgrade from .NET 6.0.110 to 6.0.111, some the of DEB content paths have eliminated intermediate folders, causing Chisel to fail to locate certain contents. This commit is fixing those paths for the affected .NET* slices.
This PR is updating the .NET* slice definitions according to the new DEBs' structures.
---
Additional info regarding the underlying .NET change: https://bugs.launchpad.net/ubuntu/+source/dotnet6/+bug/1996499
> 
> [Original Report]
> …
=> fix: dotnet* pkgs new content structure (22.04)

slices/aspnetcore-runtime-6.0.yaml
Same reason as for https://github.com/canonical/chisel-releases/pull/23. In that PR, ASPNET was forgotten, but apparently, it has also suffered the same restructuring as all other .NET runtime packages.
=> fix: aspnetcore-runtime-6.0 new content structure (22.04)

slices/aspnetcore-runtime-6.0.yaml
analogous to https://github.com/canonical/chisel-releases/pull/26
=> fix: aspnetcore-runtime-6.0 new content structure (22.10)

slices/libglib2.0-0.yaml, slices/libgraphite2-3.yaml
This PR adds libraries that Java 17 links against:  a separate slice of `libglib2` and `libgraphite2-3`
Sample docker [file](https://github.com/vpa1977/chiselled-jre/blob/mandatory-slices-demo/jre/Dockerfile.22.04).
Testing:
```
$ docker build -t jre . -f Dockerfile.22.04 --no-cache
[+] Building 152.8s (21/21) FINISHED                                                                                                                                                                    
=> [internal] load build definition from Dockerfile.22.04                                                                                                                                         0.0s
=> => transferring dockerfile: 38B …
```
=> feat: Add Java 17 runtime dependencies

slices/libapr1.yaml
This is a draft PR that adds Apache Portable library slice for Apache Tomcat native extensions. It is required to run OpenSSL TLS backend in Apache Tomcat.
Sample docker [file](https://github.com/vpa1977/chiselled-jre/blob/samples-for-17/benchmark/acmeair-tomcat/Dockerfile.distroless)
Testing:
```
$ docker build -t tomcat . -f Dockerfile.distroless 
[+] Building 2.5s (29/29) FINISHED                                              
=> [internal] load build definition from Dockerfile.distroless            0.0s
=> => transferring dockerfile: 2.68kB                                     0.0s
=> [internal] load .dockerignore                                          0.0s
=> => transferring context: 2B                                            0.0s
=> [internal] load metadata for …
```
=> feat: libapr1 - Apache Tomcat dependency

slices/base-passwd.yaml
same as https://github.com/canonical/chisel-releases/pull/12, for 22.10
=> fix: undefined variable in base-passwd mutation script, 22.10

slices/base-passwd.yaml
Fix a typo in the `base-passwd` mutation script.
=> fix: undefined variable in base-passwd mutation script, 22.04

slices/base-files.yaml, slices/base-passwd.yaml, slices/ca-certificates.yaml, slices/libc6.yaml, slices/libgcc-s1.yaml
**Duplicate of https://github.com/canonical/chisel-releases/pull/41, with a different base branch.**
This PR backports (from 22.04) and fits a few (the most basic and essential) slice definitions files into the new Focal Chisel release.
The affected packages are:
- base-files
- base-passwd
- ca-certificates
- libc6
- libgcc-s1
The choice of packages was driven by our [Chiselled Ubuntu base image](https://ubuntu.com/blog/craft-custom-chiselled-ubuntu-distroless).
=> feat: add basic slice definitions files for Focal

slices/tzdata.yaml
Introduce a new slice definition file for `tzdata`.
The slicing logic is based on:
- different regions can be installed separately;
- Europe and Asia have intertwined files, so they belong to the same slice
- standalone time zones (without location) can also be installed separately via the `zoneinfo-base`
Tested with a simple Golang app that runs in a container with and without the `zoneinfo-base` slice. With the slice, the EST printout works.
```golang
func main() {
tm := time.Now()
fmt.Printf("%s\n", tm.Local())
location, err := time.LoadLocation("EST")
if err != nil {
fmt.Println(err)
}
fmt.Println("ZONE : ", location, " Time : ", tm.In(location)) // EST
}
```
=> [22.04] create SDF for tzdata

slices/libxml2.yaml
This change adds a new slice for [libxml2](https://packages.ubuntu.com/jammy/libxml2).
=> [22.04] Add slice for libxml2

slices/libc6.yaml
Fixes #45.
libc6_libs had a path which doesn't match for various architectures such as ppc64el, s390x.
/lib/*-linux-*/ld-*.so.*:
This commit edits the path to accommodate those architectures.
=> fix(focal): invalid path in libc6_libs

slices/libbz2-1.0.yaml, slices/libdb5.3.yaml, slices/libmpdec2.yaml, slices/libncursesw6.yaml, slices/libpython3.8-minimal.yaml, slices/libpython3.8-stdlib.yaml, slices/libreadline8.yaml, slices/libtinfo6.yaml, slices/mime-support.yaml, slices/python3.8-minimal.yaml, slices/python3.8.yaml, slices/readline-common.yaml
This PR adds the necessary slices for a chiselled python3.8.
The slices should support almost all of the python3.8 standard library, except for the following modules:
- `ensurepip` (will need the `python3-pip` package)
- `tkinter`, `tkinter.*` (will need the `python3-tk` package)
* `turtle` (although this module is included, it directly depends on `tkinter`)
- `msilib`, `msvcrt`, `winreg`, `winsound` (These are MS Windows specific services and only available on MS Windows platforms)
Additionally, I intentionally did not create any `/usr/bin/python3` symlink for any possible conflicts with other future versions. Let me know if you think I should have that pointing to `/usr/bin/python3.8` anyway. Cheers!
---
<details>
<summary>python3.8 package dependencies</summary>
Here goes a …
=> focal: add python3.8 slices

slices/ncurses-base.yaml
This PR adds the slice definitions file for the package `ncurses-base`. I will be needing this for Python3.8 interactive interpreter.
=> feat(focal): add slice definitions file for ncurses-base

slices/aspnetcore-runtime-6.0.yaml, slices/base-files.yaml, slices/base-passwd.yaml, slices/ca-certificates.yaml, slices/dotnet-host.yaml, slices/dotnet-hostfxr-6.0.yaml, slices/dotnet-runtime-6.0.yaml, slices/libc6.yaml, slices/libcom-err2.yaml, slices/libcrypt1.yaml, slices/libgcc-s1.yaml, slices/libicu72.yaml, slices/libk5crypto3.yaml, slices/libkeyutils1.yaml, slices/libkrb5-3.yaml, slices/libkrb5support0.yaml, slices/liblttng-ust-common1.yaml, slices/liblttng-ust-ctl5.yaml, slices/liblttng-ust1.yaml, slices/liblzma5.yaml, slices/libnuma1.yaml, slices/libssl3.yaml, slices/libstdc++6.yaml, slices/libunwind-13.yaml, slices/libunwind8.yaml, slices/openssl.yaml, slices/zlib1g.yaml
This PR brings onto 23.10 the core slices from 23.04.
The major differences are:
- `libicu71` is renamed to `libicu72` in Mantic
=> feat: migrate slices from 23.04 to 23.10

slices/iproute2.yaml, slices/libbpf1.yaml, slices/libbsd0.yaml, slices/libcap2-bin.yaml, slices/libcap2.yaml, slices/libdb5.3.yaml, slices/libelf1.yaml, slices/libgssapi-krb5-2.yaml, slices/libmd0.yaml, slices/libmnl0.yaml, slices/libpcre2-8-0.yaml, slices/libselinux1.yaml, slices/libtirpc-common.yaml, slices/libtirpc3.yaml, slices/libxtables12.yaml, slices/libzstd1.yaml, slices/nginx-common.yaml, slices/nginx.yaml
Needs https://github.com/canonical/chisel-releases/pull/58
This PR adds the necessary slice definitions for NGINX and its dependencies. 
A couple of noteworthy mentions:
- `iproute2` is also being sliced in this PR, but is ultimately not included in the list of dependencies for Nginx. The rationale is that, although listed as a pkg dependency, `iproute2` seems to only be used by the Nginx maintainer scripts and thus not essential for a correct nginx behaviour. May `iproute2` be actually needed for nginx at runtime, we can simply uncomment that dependency later on.
- a similar rationally is being applied for `debconf` which seems to be used by some of these packages, but only for the maintainer scripts.
The following will give you a functional Nginx filesystem. `nginx-common_index` is only …
=> feat: Ubuntu 23.10 slices for NGINX

slices/base-files.yaml, slices/base-passwd.yaml, slices/ca-certificates.yaml, slices/libc6.yaml, slices/libcom-err2.yaml, slices/libcrypt1.yaml, slices/libgcc-s1.yaml, slices/libicu72.yaml, slices/libk5crypto3.yaml, slices/libkeyutils1.yaml, slices/libkrb5-3.yaml, slices/libkrb5support0.yaml, slices/liblttng-ust-common1.yaml, slices/liblttng-ust-ctl5.yaml, slices/liblttng-ust1.yaml, slices/liblzma5.yaml, slices/libnuma1.yaml, slices/libssl3.yaml, slices/libstdc++6.yaml, slices/libunwind-13.yaml, slices/libunwind8.yaml, slices/openssl.yaml, slices/zlib1g.yaml
This PR brings onto 24.04 the core slices from 23.10.
There are no changes in any of the files introduced in this PR.
=> feat: migrate slices from 23.10 to 24.04

slices/libc-bin.yaml
same as https://github.com/canonical/chisel-releases/pull/18
=> [22.10] add slice definition file for libc-bin, with nsswitch slice only

slices/libc-bin.yaml
This new slice definition file encompasses only the `nsswitch.conf` file of the libc-bin package.
=> [22.04] add slice definition file for libc-bin, with nsswitch slice only

CONTRIBUTING.md, README.md
Add the README.md and CONTRIBUTING.md files to the `main` branch.
- the README.md is currently very simple, only explaining the project and listing the existing chisel releases;
- the CONTRIBUTING.md follows our standard Canonical guidelines (e.g. CoC), and it also includes slicing instructions to set the foundations for what we expect contributors to propose
=> Add the README.md and CONTRIBUTING.md files

slices/dash.yaml
You need any shell to use an ubuntu chisel-based image in a Gitlab pipeline. Therefore I added the basic one `/bin/sh`
=> add dash package for ubuntu 23.10

slices/nginx-common.yaml
otherwise I get
```
------
> [internal] load build context:
------
ERROR: failed to solve: error from sender: failed to xattr rootfs/var/log/nginx/access.log: permission denied
```
=> fix(ubuntu-23.10): permission configuration for log files

slices/zlib1g.yaml
The libz.so files have moved location in 24.04. This commit updates the zlib1g_libs slice with proper path.
=> fix(24.04): update file path in zlib1g_libs

slices/libmpdec3.yaml, slices/libncursesw6.yaml, slices/libnsl2.yaml, slices/libpython3.11-minimal.yaml, slices/libpython3.11-stdlib.yaml, slices/libreadline8.yaml, slices/libtirpc-common.yaml, slices/libtirpc3.yaml, slices/python3.11-minimal.yaml, slices/python3.11.yaml, slices/readline-common.yaml
This PR adds the slice definition files for the Python 3.11 package and it's dependencies. The Python library packages are organized similarly to that of Python3.8 for focal: #44.
--- 
Useful diffs (trimmed):
<details>
<summary> python3.8 / python3.11 </summary>
```diff
10c10
<       - mime-support_mime-types
---
>       - media-types_data
16,17c16
<       - python3.8
<       - libpython3.8-stdlib_core
---
>       - libpython3.11-stdlib_aix-support
19a19
>       - libpython3.11-stdlib_core
21a22
>       - libpython3.11-stdlib_data-persistence
25a27
>       - libpython3.11-stdlib_extras
38d39
<       - libpython3.8-stdlib_data-persistence
42c43
<       - libpython3.8-stdlib_extras
---
>       - python3.11_core
47,48d47
<       - python3.8
<       - libpython3.8-stdlib_pydoc
49a49,50
> …
```
=> feat(22.04): add python3.11 slices and dependencies

slices/libbz2-1.0.yaml, slices/libdb5.3.yaml, slices/libexpat1.yaml, slices/libffi8.yaml, slices/libncursesw6.yaml, slices/libnsl2.yaml, slices/libpython3.11-minimal.yaml, slices/libpython3.11-stdlib.yaml, slices/libreadline8.yaml, slices/libsqlite3-0.yaml, slices/libtirpc-common.yaml, slices/libtirpc3.yaml, slices/libuuid1.yaml, slices/media-types.yaml, slices/python3.11-minimal.yaml, slices/python3.11.yaml, slices/readline-common.yaml
This PR adds the slice definition files for the Python 3.11 package and it's dependencies. The Python library packages are organized similarly to that of Python3.11 for jammy: #82.
---
<details>
<summary> Diff from the PR for jammy </summary>
```diff
$ git diff feat/22.04/python3.11 -- slices/python3.11.yaml slices/libpython3.11-minimal.yaml slices/libpython3.11-stdlib.yaml
diff --git a/slices/libpython3.11-stdlib.yaml b/slices/libpython3.11-stdlib.yaml
index ab5f7d5..1b61e98 100644
--- a/slices/libpython3.11-stdlib.yaml
+++ b/slices/libpython3.11-stdlib.yaml
@@ -326,7 +326,6 @@ slices:
numeric:
essential:
-      - libmpdec3_libs
- libpython3.11-stdlib_core
contents:
/usr/lib/python3.11/_pydecimal.py:
```
`libmpdec3` is not needed anymore.
</details>
=> feat(23.04): add python3.11 slices and dependencies

slices/tzdata.yaml
This PR adds the tzdata slices.
---
It is based on previous work for jammy in #16. There are some major changes listed below since the tzdata package changed a lot in comparison to that of jammy.
<details>
<summary> Toggle to see diff </summary>
```diff
$ git diff upstream/ubuntu-22.04 -- slices/tzdata.yaml
diff --git a/slices/tzdata.yaml b/slices/tzdata.yaml
index f0e7230..76ef9e2 100644
--- a/slices/tzdata.yaml
+++ b/slices/tzdata.yaml
@@ -14,37 +14,13 @@ slices:
/usr/share/zoneinfo/Factory:
/usr/share/zoneinfo/HST:
/usr/share/zoneinfo/iso3166.tab:
-      /usr/share/zoneinfo/leapseconds:
/usr/share/zoneinfo/leap-seconds.list:
+      /usr/share/zoneinfo/leapseconds:
/usr/share/zoneinfo/localtime:
/usr/share/zoneinfo/MET:
/usr/share/zoneinfo/MST:
/usr/share/zoneinfo/MST7MDT:
- …
```
=> feat(23.10): add tzdata slices

slices/libbz2-1.0.yaml, slices/libexpat1.yaml, slices/libffi8.yaml, slices/libncursesw6.yaml, slices/libnsl2.yaml, slices/libpython3.11-minimal.yaml, slices/libpython3.11-stdlib.yaml, slices/libreadline8.yaml, slices/libsqlite3-0.yaml, slices/libuuid1.yaml, slices/media-types.yaml, slices/python3.11-minimal.yaml, slices/python3.11.yaml, slices/readline-common.yaml
This PR adds the slice definition files for the Python 3.11 package and it's dependencies. The Python library packages are organized similarly to that of Python3.11 for lunar: #89.
---
_~~:red_circle:  Depends on #91.~~_
---
Diff in python-specific slices from 23.04 (#89):
```diff
$ git diff feat/23.04/python3.11 -- slices/*python*
diff --git a/slices/libpython3.11-stdlib.yaml b/slices/libpython3.11-stdlib.yaml
index 1b61e98..3903e3d 100644
--- a/slices/libpython3.11-stdlib.yaml
+++ b/slices/libpython3.11-stdlib.yaml
@@ -120,6 +120,7 @@ slices:
data-types:
essential:
- libpython3.11-stdlib_core
+      - tzdata_zoneinfo
contents:
/usr/lib/python3.11/graphlib.py:
/usr/lib/python3.11/lib-dynload/_zoneinfo.cpython-311-*-linux-*.so:
```
=> feat(23.10): add python3.11 slices and dependencies

slices/libbz2-1.0.yaml, slices/libdb5.3.yaml, slices/libexpat1.yaml, slices/libffi8.yaml, slices/libgssapi-krb5-2.yaml, slices/libncursesw6.yaml, slices/libnsl2.yaml, slices/libpython3.11-minimal.yaml, slices/libpython3.11-stdlib.yaml, slices/libreadline8.yaml, slices/libsqlite3-0.yaml, slices/libtirpc-common.yaml, slices/libtirpc3.yaml, slices/libuuid1.yaml, slices/media-types.yaml, slices/python3.11-minimal.yaml, slices/python3.11.yaml, slices/readline-common.yaml
This PR adds the slice definition files for the Python 3.11 package and it's dependencies. The Python library packages are organized similarly to that of Python3.11 for mantic: #90.
---
:red_circle: Depends on the following PRs:
---
Diff in python-specific slices from 23.10 (#90):
```diff
$ git diff feat/23.10/python3.11 -- slices/*python*
diff --git a/slices/libpython3.11-stdlib.yaml b/slices/libpython3.11-stdlib.yaml
index 3903e3d..39fdfa4 100644
--- a/slices/libpython3.11-stdlib.yaml
+++ b/slices/libpython3.11-stdlib.yaml
@@ -18,6 +18,7 @@ slices:
- liblzma5_libs
- libpython3.11-minimal_libs
- media-types_data
+      - netbase_config
contents:
/usr/lib/python3.11/_bootsubprocess.py:
/usr/lib/python3.11/_compression.py:
```
=> feat(24.04): add python3.11 slices and dependencies

chisel.yaml
This PR adds the Ubuntu Archive Automatic Signing Key (2018) as a "public-key" in the chisel.yaml. The armored data was obtained by executing the following commands on a Ubuntu 22.04 machine:
$ gpg --keyserver keyserver.ubuntu.com --receive-keys 871920D1991BC93C
$ gpg --armor --export 871920D1991BC93C
~~BREAKING CHANGE: This PR introduces the new chisel yaml format "chisel-v2", in which ``public-keys`` (top-level) and ``archive.<name>.public-keys`` fields are introduced.~~ This changes is related to the addition of integrity checks in chisel. [1]
[1] https://github.com/canonical/chisel/pull/106
=> feat(22.04): add ubuntu archive signing key 2018

chisel.yaml
This PR adds the Ubuntu Archive Automatic Signing Key (2018) as a "public-key" in the chisel.yaml. The armored data was obtained by executing the following commands on a Ubuntu 22.04 machine:
$ gpg --keyserver keyserver.ubuntu.com --receive-keys 871920D1991BC93C
$ gpg --armor --export 871920D1991BC93C
BREAKING CHANGE: This PR introduces the new chisel yaml format "chisel-v2", in which ``public-keys`` (top-level) and ``archive.<name>.public-keys`` fields are introduced. This change is related to the addition of integrity checks in chisel. [1]
[1] https://github.com/canonical/chisel/pull/106
=> feat(24.04): add ubuntu archive signing key 2018

chisel.yaml
This PR adds the Ubuntu Archive Automatic Signing Key (2018) as a "public-key" in the chisel.yaml. The armored data was obtained by executing the following commands on a Ubuntu 22.04 machine:
$ gpg --keyserver keyserver.ubuntu.com --receive-keys 871920D1991BC93C
$ gpg --armor --export 871920D1991BC93C
~~BREAKING CHANGE: This PR introduces the new chisel yaml format "chisel-v2", in which ``public-keys`` (top-level) and ``archive.<name>.public-keys`` fields are introduced.~~ This changes is related to the addition of integrity checks in chisel. [1]
[1] https://github.com/canonical/chisel/pull/106
=> feat(20.04): add ubuntu archive signing key 2018

chisel.yaml
This PR adds the Ubuntu Archive Automatic Signing Key (2018) as a "public-key" in the chisel.yaml. The armored data was obtained by executing the following commands on a Ubuntu 22.04 machine:
$ gpg --keyserver keyserver.ubuntu.com --receive-keys 871920D1991BC93C
$ gpg --armor --export 871920D1991BC93C
~~BREAKING CHANGE: This PR introduces the new chisel yaml format "chisel-v2", in which ``public-keys`` (top-level) and ``archive.<name>.public-keys`` fields are introduced.~~ This change is related to the addition of integrity checks in chisel. [1]
[1] https://github.com/canonical/chisel/pull/106
=> feat(23.04): add ubuntu archive signing key 2018

slices/openssl.yaml
`/usr/lib/ssl/certs` is a symlink to `/etc/ssl/certs`. But the latter was not included in the slice, resulting in a broken symlink in the rootfs if the ca-certificates slices were not installed.
This PR adds the missing `/etc/ssl/certs` path.
=> fix(20.04): add missing path in openssl_config

slices/openssl.yaml
`/usr/lib/ssl/certs` is a symlink to `/etc/ssl/certs`. But the latter was not included in the slice, resulting in a broken symlink in the rootfs if the ca-certificates slices were not installed.
This PR adds the missing `/etc/ssl/certs` path.
=> fix(24.04): add missing path in openssl_config

slices/findutils.yaml
Adds `findutils` slice def to 22.04, to support running `find` and `xargs` in chiseled containers.
=> feat(22.04): Add findutils slice

slices/findutils.yaml
Adds findutils slice def to 23.10, to support running `find` and `xargs` in chiseled containers.
(see #105)
=> feat(23.10): Add findutils slice

slices/findutils.yaml
Adds findutils slice def to 24.04, to support running `find` and `xargs` in chiseled containers.
(see #105)
=> feat(24.04): Add findutils slice

slices/grep.yaml
Add `grep` slice for Ubuntu 22.04.
Supports running `grep`, `egrep`, etc.
=> feat(22.04): Add grep slice

slices/libdb5.3.yaml, slices/libgmp10.yaml, slices/libgnutls30.yaml, slices/libhogweed6.yaml, slices/libidn2-0.yaml, slices/libldap-2.5-0.yaml, slices/libnettle8.yaml, slices/libp11-kit0.yaml, slices/libsasl2-2.yaml, slices/libsasl2-modules-db.yaml, slices/libtasn1-6.yaml, slices/libunistring2.yaml
A few slice definition files in the ubuntu-22.04 release contains Byte Order Mark (BOM) [1-2]. This is not needed for our purposes and ASCII text is fine for the slice definition files at the moment. Hence, this PR removes all the BOMs from the files in this branch.
Note: to check the status of the files, you may run
file chisel.yaml slices/*
Refernces:
1. https://en.wikipedia.org/wiki/Byte_order_mark
2. https://stackoverflow.com/q/2223882
=> fix(22.04): remove Byte Order Marks from files

slices/libgcc-s1.yaml
The `libgcc_s.so` path [has changed in the libgcc-s1 package in 24.04](https://packages.ubuntu.com/noble/amd64/libgcc-s1/filelist). This PR updates the new path in the slice definition file.
=> hotfix(24.04): broken path in libgcc-s1_libs

slices/libgmp10.yaml
A few slice definition files in the ubuntu-23.10 release contain Byte Order Mark (BOM) [1-2]. This is not needed for our purposes and ASCII text is currently fine for the slice definition files. Hence, this PR removes all the BOMs from the files in this branch.
Note: to check the status of the files, you may run
file chisel.yaml slices/*
Refernces:
1. https://en.wikipedia.org/wiki/Byte_order_mark
2. https://stackoverflow.com/q/2223882
---
Related: https://github.com/canonical/chisel-releases/pull/115
=> fix(23.10): remove Byte Order Marks from files

slices/dash.yaml
Adds slice for `dash` (already exists in `23.10` and `24.04`).
=> feat(22.04): add slice for dash

slices/grep.yaml
Add `grep` slice for Ubuntu 23.10.
Supports running `grep`, `egrep`, etc.
=> feat(23.10): add grep slice

slices/grep.yaml
As noted in #117 amd #118 by @cjdcordeiro  the `deprecated` slice is missing an essential def for `libpcre3`. Backports the fix from those PRs to 22.04.
=> feat(22.04): Use dash instead of bash for grep deprecated slice

slices/grep.yaml
Add `grep` slice for Ubuntu 24.04.
Supports running `grep`, `egrep`, etc.
=> feat(24.04): add grep slice

slices/base-files.yaml
On full Ubuntu VMs/hardware installs, as well as the upstream Ubuntu containers, /var/run is a symlink to /run. Chiseled containers do not make this symlink - this causes issues with Docker Swarm installs (and probably other projects), which mount secrets into /run.
=> bug(24.04): make /var/run a symlink to /run

slices/base-files.yaml
On full Ubuntu VMs/hardware installs, as well as the upstream Ubuntu containers, `/var/run` is a symlink to `/run`. Chiseled containers do not make this symlink - this causes issues with Docker Swarm installs (and probably other projects), which mount secrets into `/run`.
=> bug(22.04): make /var/run a symlink to /run

slices/base-files.yaml
On full Ubuntu VMs/hardware installs, as well as the upstream Ubuntu containers, /var/run is a symlink to /run. Chiseled containers do not make this symlink - this causes issues with Docker Swarm installs (and probably other projects), which mount secrets into /run.
=> bug(23.10): make /var/run a symlink to /run

slices/libcrypt1.yaml, slices/libkeyutils1.yaml, slices/libselinux1.yaml
The file paths seems to have changed. This fixes it. Needed by #135 and #137
=> fix(24.04): library paths for libcrypt1, libkeyutils1 and libselinux1

.github/scripts/install_slices/install_slices.py, .github/scripts/install_slices/test_install_slices.py
Archive version was being changed to 23.1 instead 23.10 for values with trailing zeroes. This PR fixes the bug.
https://github.com/canonical/chisel-releases/actions/runs/8014505888/job/21893215155?pr=14
=> chore: fix archive version while logging

.github/workflows/ci.yaml
This commit adds a workflow to test installing changed or all slices, based on the files changed.
---
Equivalent of #120.
=> chore(23.10): add workflow to test slices

slices/openjdk-8-jre-headless.yaml
Same as #149 
@vpa1977 can you also pls double check this one?
=> fix(20.04): fix arch specific paths for openjdk-8

slices/openjdk-8-jre-headless.yaml
Certain paths were not valid for all architectures. This PR adds the arch-specific constraints.
@vpa1977 can you pls double check if it makes sense?
=> fix(22.04): fix arch specific paths for openjdk-8

.github/workflows/cla-check.yaml
The proposed GH workflow will check if the author of the PR has signed our CLA.
This is a reusable workflow that can be called from the release branches.
Tested in https://github.com/cjdcordeiro/chisel-releases/actions/runs/7876013322.
=> ci(cla-check): add CLA check for the repo

.github/workflows/ci.yaml
This PR removes the `on: push` event from the CI. This means that the CIs in `ubuntu-*` branches will not run on `push`.
* https://github.com/canonical/chisel-releases/pull/157#pullrequestreview-1909130701
* #172
=> chore(20.04): CI does not run on push

.github/workflows/ci.yaml
This PR removes the `on: push` event from the CI. This means that the CIs in `ubuntu-*` branches will not run on `push`.
* https://github.com/canonical/chisel-releases/pull/157#pullrequestreview-1909130701
* #172
=> chore(23.10): CI does not run on push

.github/workflows/ci.yaml
This PR removes the `on: push` event from the CI. This means that the CIs in `ubuntu-*` branches will not run on `push`.
* https://github.com/canonical/chisel-releases/pull/157#pullrequestreview-1909130701
* #172
=> chore(24.04): CI does not run on push

.github/workflows/install-slices.yaml
This PR adds changes which ensure that in a PR or Push where all files are not installed, missing packages for one or more architectures will be ignored if they exist for at least one arch.
Relevant: https://github.com/canonical/chisel-releases/pull/149#issuecomment-1961757405
=> chore: ignore missing packages for PRs, Push

.github/workflows/ci.yaml, chisel.yaml, slices/base-files.yaml, slices/base-passwd.yaml, slices/bash.yaml, slices/ca-certificates.yaml, slices/findutils.yaml, slices/grep.yaml, slices/libc6.yaml, slices/libpython3.11-stdlib.yaml, slices/libtinfo6.yaml, slices/libunwind8.yaml, slices/nodejs.yaml, slices/openssl.yaml, slices/python3.11.yaml, slices/tzdata.yaml
This PR adds a "Lint" job to lint the slices and chisel.yaml.
* #147
* #177
* #178
=> chore(24.04): add lint job

.github/workflows/install-slices.yaml
Whenever there is a PR to the `main` branch, the scripts may be updated. Use the updated changes from the `head_ref` in the CI, to run the installability tests.
=> chore: use updated scripts for PRs to main

.github/workflows/ci.yaml, chisel.yaml, slices/base-files.yaml, slices/base-passwd.yaml, slices/bash.yaml, slices/ca-certificates-java.yaml, slices/ca-certificates.yaml, slices/fonts-dejavu-core.yaml, slices/libc6.yaml, slices/libfontconfig1.yaml, slices/libfreetype6.yaml, slices/libglib2.0-0.yaml, slices/libmount1.yaml, slices/libnss3.yaml, slices/libpython3.8-minimal.yaml, slices/libpython3.8-stdlib.yaml, slices/libreadline8.yaml, slices/libunwind8.yaml, slices/openjdk-8-jre-headless.yaml, slices/openssl.yaml, slices/python3.8-minimal.yaml, slices/python3.8.yaml
This PR adds a "Lint" job to lint the slices and chisel.yaml.
* #147
=> chore(20.04): add lint job

.github/workflows/install-slices.yaml
Currently we are running Installability Tests whenever a file inside ".github" directory is added or modified. We do not always need this. Instead, checking whether the relevant workflow file and scripts have changed is enough.
=> chore: run installability tests only on relevance

.github/scripts/pkg-deps/pkg-deps, .github/workflows/pkg-deps.yaml
This PR adds a new reusable workflow which can be run on Pull Requests to see if the packages listed in "essential" of a slice are the true dependencies of the slice package. This workflow will add a PR comment if it finds any errors.
https://github.com/canonical/chisel-releases/pull/188
See demo at https://github.com/rebornplusplus/chisel-releases/pull/9.
=> chore: add workflow to check package dependencies

.github/workflows/ci.yaml
This PR adds a new pkg-deps job on Pull Request. It checks in changed files if slices of any package A has been listed in "essential" of a slice in package B, but B does not depend on A. If found, the CI will add a comment in the Pull Request with the findings.
#187
See demo at https://github.com/rebornplusplus/chisel-releases/pull/9.
=> chore(22.04): add pkg-deps job

slices/libc-bin.yaml
feat(24.04): add slice for libc-bin_locale
#184
#185
```bash
$ chisel cut --release chisel-releases/ --root foo libc-bin_locale
2024/03/07 10:37:28 Processing chisel-releases/ release...
2024/03/07 10:37:28 Selecting slices...
2024/03/07 10:37:28 Fetching ubuntu 24.04 noble suite details...
2024/03/07 10:37:29 Release date: Thu, 07 Mar 2024 14:27:20 UTC
2024/03/07 10:37:29 Fetching index for ubuntu 24.04 noble main component...
2024/03/07 10:37:29 Fetching index for ubuntu 24.04 noble universe component...
2024/03/07 10:37:30 Fetching ubuntu 24.04 noble-security suite details...
2024/03/07 10:37:30 Release date: Thu, 04 Jan 2024 18:43:12 UTC
2024/03/07 10:37:30 Fetching index for ubuntu 24.04 noble-security main component...
2024/03/07 10:37:30 Fetching index for ubuntu 24.04 …
```
=> feat(24.04): add slice for libc-bin_locale

.github/scripts/pkg-deps/pkg-deps, .github/workflows/pkg-deps.yaml
This PR amends the `pkg-deps` workflow to support `pull_request_target` events, which is what we will be needing from the caller workflow.
22.04: #199 
=> chore(main): pkg-deps workflow supports pull_request_target

.github/workflows/ci-pr-target.yaml, .github/workflows/ci.yaml
This PR fixes the `pkg-deps` job with proper `event` and permissions. The `pkg-deps` job is moved from the `ci.yaml` workflow to a new `ci-pr-target.yaml` workflow which accommodates jobs which need the `pull_request_target` event.
#198
=> chore(22.04): fix pkg-deps job

.github/workflows/ci-pr-target.yaml
This PR adds a new pkg-deps job on Pull Request. It checks in changed files if slices of any package A has been listed in "essential" of a slice in package B, but B does not depend on A. If found, the CI will add a comment in the Pull Request with the findings.
#199
=> chore(20.04): add pkg-deps job

.github/workflows/ci-pr-target.yaml
This PR adds a new pkg-deps job on Pull Request. It checks in changed files if slices of any package A has been listed in "essential" of a slice in package B, but B does not depend on A. If found, the CI will add a comment in the Pull Request with the findings.
#199
#200
=> chore(23.10): add pkg-deps job

.github/workflows/ci-pr-target.yaml
This PR adds a new pkg-deps job on Pull Request. It checks in changed files if slices of any package A has been listed in "essential" of a slice in package B, but B does not depend on A. If found, the CI will add a comment in the Pull Request with the findings.
- #199
- #200
- #201 
=> chore(24.04): add pkg-deps job

.github/workflows/ci-pr-target.yaml
This fixes the bad repo (typo) for calling reusable workflow.
```bash
```
=> fix(ci): wrong repo for reusable workflow

.github/workflows/ci-pr-target.yaml
This fixes the bad repo (typo) for calling reusable workflow.
```bash
```
=> fix(ci): 23.10 wrong repo for reusable workflow

.github/workflows/ci-pr-target.yaml
This fixes the bad repo (typo) for calling reusable workflow.
```bash
```
=> fix(ci): 24.04 wrong repo for reusable workflow

slices/sed.yaml
Add simple slice for `sed` - we use it in a bunch of our entrypoints.
No forward ports necessary
```bash
rm -rf fs && \
mkdir -p fs && \
~/go/bin/chisel cut --root=$(readlink -f fs) --release=$(readlink -f .) sed_bins && \
sudo chroot fs /usr/bin/sed --version
```
Should show similar output to other PRs, but I don't have a 24.04 system that will play nice with my build infrastructure to test right now.
=> feat(24.04): add sed slices

slices/tzdata.yaml
This PR fixes a minor typo in the tzdata slice.
n/a
It only fixes the typo for the two versions with the tzdata slices (22.04 and 23.04).
n/a
n/a
=> chore(23.04): Fix minor typo in "countries"

chisel.yaml
Bumps the `format` to **v1**, in line with the announced schema changes in https://discourse.ubuntu.com/t/chisel-v0-9-0-is-out/41759.
=> feat(24.04): bump format to v1

slices/tzdata.yaml
This PR fixes a minor typo in the tzdata slice.
n/a
It only fixes the typo for the two versions with the tzdata slices (22.04 and 23.04).
n/a
n/a
=> chore(22.04): Fix minor typo in "countries"

slices/libcrypto++8t64.yaml
Add libcrypto++8t64 to 24.04
/closes #241 
=> feat(24.04): add libcrypto++8t64 slice

slices/init-system-helpers.yaml, slices/libcap2.yaml, slices/libgcrypt20.yaml, slices/libgpg-error0.yaml, slices/liblz4-1.yaml, slices/libproc2-0.yaml, slices/libsystemd0.yaml, slices/procps.yaml
Add procps slice and dependencies.
I'm not sure what to do with this content for `procps`:
```shell
/usr/lib/sysctl.d/99-protect-links.conf
/etc/init.d/procps
/etc/sysctl.conf
/etc/sysctl.d/10-console-messages.conf
/etc/sysctl.d/10-ipv6-privacy.conf
/etc/sysctl.d/10-kernel-hardening.conf
/etc/sysctl.d/10-magic-sysrq.conf
/etc/sysctl.d/10-map-count.conf
/etc/sysctl.d/10-network-security.conf
/etc/sysctl.d/10-ptrace.conf
/etc/sysctl.d/10-zeropage.conf
```
Not sure if I should add a `config:` slice, any guidance is appreciated.
/closes #236 
=> 24.04/add procps

slices/libboost-context1.83.0.yaml, slices/libboost-coroutine1.83.0.yaml, slices/libboost-filesystem1.83.0.yaml, slices/libboost-log1.83.0.yaml, slices/libboost-thread1.83.0.yaml
As part of the issue #244 , this PR will add some of the packages.
#224
```bash
chisel cut \
--release ./ \
--root rootfs \
libboost-coroutine1.83.0_libs libboost-context1.83.0_libs libboost-filesystem1.83.0_libs libboost-log1.83.0_libs
2024/05/10 11:58:50 Processing ./ release...
2024/05/10 11:58:50 Selecting slices...
2024/05/10 11:58:50 Fetching ubuntu 24.04 noble suite details...
2024/05/10 11:58:50 Release date: Thu, 25 Apr 2024 15:10:33 UTC
2024/05/10 11:58:50 Fetching index for ubuntu 24.04 noble main component...
2024/05/10 11:58:50 Fetching index for ubuntu 24.04 noble universe component...
2024/05/10 11:58:51 Fetching ubuntu 24.04 noble-security suite details...
2024/05/10 11:58:51 Release date: Thu, 09 May 2024 16:53:41 UTC
2024/05/10 11:58:51 Fetching index for ubuntu 24.04 …
```
=> 24.04/add some libboost 1.83 slices

slices/libpq5.yaml
Slicing `libpq5` used to access posgres databases
N/A
N/A
Start a docker container running ubuntu-22.04 while being in this repository folder and a postgres database
```
docker run --name postgres -e POSTGRES_PASSWORD=secret -d postgres:15
#Get this container IP address using docker inspect postgres and note it
docker run -d --name flask -v $(pwd):/home/chisel ubuntu:22.04 sleep 3600
docker exec -ti flask bash
apt update && apt install -y golang-1.22 ca-certificates curl python3-venv git
update-alternatives --install /usr/bin/go go /usr/lib/go-1.22/bin/go 0
go install github.com/canonical/chisel/cmd/chisel@latest
/root/go/bin/chisel cut --release /home/chisel/ --root / libpq5_libs
cd /home
git clone https://github.com/canonical/sample-flask.git
cd sample-flask
git checkout feat-database …
```
=> Slicing libpq5 required in python to access a posgres database

slices/libpython3.11-stdlib.yaml, slices/python3-distutils.yaml, slices/python3-lib2to3.yaml, slices/python3-pip-whl.yaml, slices/python3-setuptools-whl.yaml, slices/python3.11-venv.yaml
Adding `python3.11-venv` chiseled package and its dependency.
The aim is to be able to use the python plugin on `rockcraft` entirely with chiseled packages, allowing very small OCI images for python applications.
N/A
N/A
To test in a VM, start an `ubuntu-22.04`, copy this branch into `/home/chisel` folder (or mount it):
```bash
apt update && apt install -y golang-1.22 ca-certificates
update-alternatives --install /usr/bin/go go /usr/lib/go-1.22/bin/go 0
go install github.com/canonical/chisel/cmd/chisel@latest
/root/go/bin/chisel cut --release /home/chisel/ --root / python3.11-venv_libs
cd ~
mkdir test
cd test
python3.11 -m venv env
echo "flask" > requirements.txt
source env/bin/activate
pip install -r requirements.txt
```
To test using rockcraft use the following `rockcraft.yaml` at the …
=> Add python3.11-venv slices to ubuntu-22.04

slices/python3-distutils.yaml
2 modules of `python3-distutils` using Python3.11 depends on `python3-lib2to3` even if not used by upstream `python3.11-venv` this could break some usecase.
Therefore I added python3-lib2to3 as dependency for Python3.11 in python3-distutils
Related to: https://github.com/canonical/chisel-releases/pull/259
python3-distutils doesn't exists anymore in Python3.12 using by Ubuntu 24.04
N/A
N/A
=> Add lib2to3 as dep of distutils for python 3.11

slices/libpython3.10-minimal.yaml, slices/libpython3.10-stdlib.yaml, slices/python3-distutils.yaml, slices/python3.10-minimal.yaml, slices/python3.10-venv.yaml, slices/python3.10.yaml
Adding python3.10-venv chiseled package and its dependency, including python3.10
The aim is to be able to use the python plugin on rockcraft entirely with chiseled packages, allowing very small OCI images for python applications.
N/A
Python3.12 is available on Noble and is the default Python version for noble
To test in a VM, start an `ubuntu-22.04`, copy this branch into `/home/chisel` folder (or mount it):
```bash
apt update && apt install -y golang-1.22 ca-certificates
update-alternatives --install /usr/bin/go go /usr/lib/go-1.22/bin/go 0
go install github.com/canonical/chisel/cmd/chisel@latest
/root/go/bin/chisel cut --release /home/chisel/ --root / python3.10-venv_ensurepip
cd ~
mkdir test
cd test
python3.10 -m venv env
echo "flask" > requirements.txt
source env/bin/activate
pip …
```
=> Draft: feat(22.04): Slicing python3.10-venv and python3.10

.github/workflows/spread.yaml
This PR introduces a new reusable GitHub workflow for running Spread tests. 
Each branch will have its own `spread.yaml` configuration, and this workflow will be called from the branches, on every PR. 
The tests shall only run for:
- the SDFs which are added or modified
- the tests which are added or modified 
Tested the execution of this workflow here:
- https://github.com/cjdcordeiro/chisel-releases/pull/11 (with additional mock commits to ensure the logic works when filtering the added and modified files)
- https://github.com/cjdcordeiro/chisel-releases/pull/13
=> ci(spread): add reusable workflow for Spread tests

slices/openssl.yaml
Add `openssl_data` slice for users does not require the "openssl" binaries, but only needs the `pem` bundled certificate at the default `cafile`.
The problem: Programmes in rocks with base focal and jammy cannot get local issuer certificates during an SSL certificate verification.
The cause: The lack of both the symlinks of certificates and rehashed symlinks to the certificates in `/etc/ssl/certs` that point to the certificates introduced by package "ca-certificates" and the symlink pointing to the ca-certificates bundle crt file.
To cope with this problem, we are diverging a bit from the behaviour of the package "openssl" in focal and jammy, providing the symlink `/usr/lib/ssl/cert.pem -> /etc/ssl/certs/ca-certificates.crt` in the slice `openssl_data`. The reasons behind that are: 
1. …
=> feat(20.04): add 'data' slice to openssl SDF

slices/ca-certificates.yaml
Fix non-existing slice name in the slice definition file of `ca-certificates`.
#285 
=> fix(24.04): slice name non-exist in comment

.github/workflows/ci.yaml, README.md, slices/libpython3.12-stdlib.yaml, spread.yaml, tests/spread/integration/base-passwd/task.yaml, tests/spread/integration/python3.12/task.yaml, tests/spread/integration/python3.12/test_core.py, tests/spread/integration/python3.12/test_standard.py, tests/spread/lib/install-slices
needs https://github.com/canonical/chisel-releases/pull/280
This PR adds the Spread configurations to this branch. It also adds a couple of initial tests for existing package slices.
In addition, it also fixes a missing dependency for Python3.12 on armhf (identified via the tests :smile: )
https://github.com/canonical/chisel-releases/pull/280
Tested the execution of this workflow here:
- https://github.com/cjdcordeiro/chisel-releases/pull/11 (with additional mock commits to ensure the logic works when filtering the added and modified files)
- https://github.com/cjdcordeiro/chisel-releases/pull/13
=> ci(spread): support slice testing through Spread

README.md
Update README on main branch to mark mantic as EOL
#284
Does not apply
Does not apply
https://fridge.ubuntu.com/2024/06/05/ubuntu-23-10-mantic-minotaur-reaches-end-of-life-on-july-11-2024/
> Ubuntu 23.10 will reach end of life on July 11, 2024.
=> docs: mark mantic as EOL

.github/workflows/spread.yaml
The Spread workflow was using the head repo at checkout time, which means the files diff was being calculated against the forked repository instead of the upstream `chisel-releases`. The consequence of that is that we could get:
- bad Spread diffs and executions if the fork is out of date
- Spread CI errors if the fork does not have the base branch (e.g.: https://github.com/canonical/chisel-releases/actions/runs/10076017309/job/27855492015)
This PR fixes the Spread CI checkout.
Tested:
- https://github.com/cjdcordeiro/chisel-releases/actions/runs/10076340176/job/27856511632?pr=15 and
- https://github.com/cjdcordeiro/chisel-releases/actions/runs/10076339238/job/27856507877?pr=16 …
=> ci(spread): fix checkout ref

.github/pull_request_template.md, .github/workflows/spread.yaml, CONTRIBUTING.md
Ensure the Spread testing instructions are part of the contributing guidelines, and that the PR description template is also updated accordingly.
#281 
#290 
#289 
=> docs: add testing instructions in CONTRIBUTING.md

.github/workflows/spread.yaml, CONTRIBUTING.md
Use the LXD backend instead of Docker. Thus we need to install and setup LXD and also run in amd64 and arm cause LXD will not have emulation, like Docker.
#316 
See a test here: https://github.com/cjdcordeiro/chisel-releases/actions/runs/10492345808/job/29063655589?pr=17
=> ci: run the Spread tests with the LXD backend

.github/workflows/spread.yaml
Don't run Spread unless there are changes to be tested.
See the tests:
- with nothing to test: https://github.com/cjdcordeiro/chisel-releases/actions/runs/10582799893/job/29323510725?pr=19
- with something to test: https://github.com/cjdcordeiro/chisel-releases/actions/runs/10582972298/job/29323884602?pr=19
=> ci: only run spread when there are changes

spread.yaml, tests/spread/integration/openssl/task.yaml
=> test(24.04): add LXD backend to Spread

slices/libmount1.yaml
https://github.com/canonical/chisel-releases/pull/274 referenced libssecomp2 copyright instead of libmount1. Use libmount1 copyright.
[](https://github.com/canonical/chisel-releases/pull/274)
n/a
=> fix(24.04): use correct libmount1 copyright

slices/libblas3.yaml, slices/libbs2b0.yaml, slices/libchromaprint1.yaml, slices/libelf1t64.yaml, slices/libflac12t64.yaml, slices/libllvm17t64.yaml, slices/libopenmpt0t64.yaml, slices/libpciaccess0.yaml, slices/librav1e0.yaml, slices/librubberband2.yaml, slices/libvidstab1.1.yaml, slices/libvorbis0a.yaml, slices/libvorbisenc2.yaml, slices/libvorbisfile3.yaml, slices/libwebpmux3.yaml, slices/libx265-199.yaml, slices/libxml2.yaml
The overall goal is to create a SDF for the `ffmpeg` package. Since ffmpeg has a pretty deep dependency tree, this is broken up in a series of smaller PRs (see #297 and #252). This PR adds SDF for the following packages that are all transitive dependencies of ffmpeg:
* libblas3
* libbs2b0
* libchromaprint1
* libelf1t64
* libflac12t64
* libllvm17t64
* libopenmpt0t64
* libpciaccess0
* librav1e0
* librubberband2
* libvidstab1.1
* libvorbis0a
* libvorbisenc2
* libvorbisfile3
* libwebpmux3
* libx265-199
* libxml2
Followup of #297 and #252
* Note: I did not add new spread tests since those are all `libs` slices 
=> feat(24.04): add ffmpeg dependencies slices

slices/libblas3.yaml
The `libblas3` package post install scripts create a symbolic link that is currently missing from the corresponding package slice, leading to errors finding the lib when trying to run a program that links against it:
```sh
ffmpeg: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory
```
=> fix(24.04): add missing symlink for `libblas3`

slices/libharfbuzz0b.yaml, tests/spread/integration/libharfbuzz0b/task.yaml, tests/spread/integration/libharfbuzz0b/test.c
The slice is required as a generic openjdk awt dependency. It is used by OpenJDK libfontmanager.
[openjdk-21](https://github.com/canonical/chisel-releases/pull/313)
=> feat(24.04): libharfbuzz0b slice

slices/diffutils.yaml, slices/dpkg.yaml, slices/libc-bin.yaml, slices/tar.yaml, tests/spread/integration/diffutils/task.yaml, tests/spread/integration/dpkg/task.yaml, tests/spread/integration/tar/task.yaml
- Adds an `ldconfig` slice for `libc-bin`
- Adds slices for `diffutils`, `dpkg` and `tar`
- Adds an integration test for a basic `dpkg` package.
This is a newer subset of https://github.com/canonical/chisel-releases/pull/136/files
Eventually this should allow `snapcraft`, `charmcraft`, etc. to use chiseled versions of apt.
=> feat(24.04): add dpkg and dependencies

.github/workflows/install-slices.yaml
For installing slices within the CI, we want to use the latest dev version of Chisel (in `main`) instead of the latest release.
#226 
=> ci: use Chisel from main

slices/liblzo2-2.yaml, slices/squashfs-tools.yaml, tests/spread/integration/squashfs-tools/task.yaml
=> feat(24.04): add squashfs-tools

slices/base-files.yaml
This commit adds a new slice ``base-files_chisel`` which does not extract anything from the package, rather comes with an artificial path where the Chisel DB should be generated.
This commit is the first one to introduce the "generate" keyword to paths. The "generate" keyword is designed to _generate_ various bookkeeping stuff for a chiselled file system. Right now, it only supports one value: "manifest". Mark a path with "generate: manifest" to generate a Chisel DB at that location. Please note that, the marking path must be in the following format:
/absolute/path/to/dir/**
The path must be an absolute directory path with no wildcard in it's name followed by trailing ** which makes sure nothing else is generated in that directory.
- #226 
- #358
=> feat(24.04): add slice to generate DB

slices/base-files.yaml
This commit adds a new slice ``base-files_chisel`` which does not extract anything from the package, rather comes with an artificial path where the Chisel DB should be generated.
This commit is the first one to introduce the "generate" keyword to paths. The "generate" keyword is designed to _generate_ various bookkeeping stuff for a chiselled file system. Right now, it only supports one value: "manifest". Mark a path with "generate: manifest" to generate a Chisel DB at that location. Please note that, the marking path must be in the following format:
/absolute/path/to/dir/**
The path must be an absolute directory path with no wildcard in it's name followed by trailing ** which makes sure nothing else is generated in that directory.
- #226 
- #357
=> feat(20.04): add slice to generate DB

slices/openjdk-21-jre-headless.yaml
jvm.cfg-default is a packaging artifact:
[d/rules](https://salsa.debian.org/openjdk-team/openjdk/-/blob/master/debian/rules?ref_type=heads#L1335)
It is not needed for the runtime and is provided as a sample of JVM config file.
=> fix(openjdk-21): remove jvm.cfg-default (packaging)

spread.yaml
Chisel's v1.0.0 has 2 release assets per architecture now. This PR fixes the installation of Chisel in the spread system and add integrity verification of the downloaded binary.
Quick test via: `spread lxd:tests/spread/integration/base-passwd`
=> fix(spread): check chisel binary integrity

slices/wget.yaml, tests/spread/integration/wget/task.yaml
Add slices for gnu wget.
This change adds the GNU variant of `wget`.
Assuming this change is approved I'm happy to also PR for 24.10.
I have manually tested the installation and usage of the slice.
=> feat(24.04): add wget slices

chisel.yaml
This PR adds `default: true` to the `ubuntu` archive in chisel.yaml. This is being added due to chisel supporting multiple archives now: https://github.com/canonical/chisel/commit/7eb8428f432557aeaa502fec8ee7c28aa0c8d271.
Related:
=> fix(24.10): add default archive in chisel.yaml

chisel.yaml
This PR adds `default: true` to the `ubuntu` archive in chisel.yaml. This is being added due to chisel supporting multiple archives now: https://github.com/canonical/chisel/commit/7eb8428f432557aeaa502fec8ee7c28aa0c8d271.
Related:
=> fix(24.04): add default archive in chisel.yaml

chisel.yaml
This PR adds `default: true` to the `ubuntu` archive in chisel.yaml. This is being added due to chisel supporting multiple archives now: https://github.com/canonical/chisel/commit/7eb8428f432557aeaa502fec8ee7c28aa0c8d271.
Related:
=> fix(22.04): add default archive in chisel.yaml

chisel.yaml
This PR adds `default: true` to the `ubuntu` archive in chisel.yaml. This is being added due to chisel supporting multiple archives now: https://github.com/canonical/chisel/commit/7eb8428f432557aeaa502fec8ee7c28aa0c8d271.
Related:
=> fix(20.04): add default archive in chisel.yaml

spread.yaml, tests/spread/integration/dash/task.yaml
This fixes an error where spread tests on docker for armhf was failing the preparation step due to getting both the arm and arm64 downloads.
- [Jammy](https://github.com/canonical/chisel-releases/pull/369)
- [Noble](https://github.com/canonical/chisel-releases/pull/370)
=> fix(spread-24.10): make spread work on armhf

spread.yaml, tests/spread/integration/dash/task.yaml
This fixes an error where spread tests on docker for armhf was failing the preparation step due to getting both the arm and arm64 downloads.
- [Jammy](https://github.com/canonical/chisel-releases/pull/369)
- [Oracular](https://github.com/canonical/chisel-releases/pull/371)
=> fix(spread-24.04): make spread work on armhf

.github/workflows/spread.yaml
Update the [changed-files](https://github.com/tj-actions/changed-files) github action to version 45. Versions before 41 are subject to a command injection vulnerability, see https://github.com/advisories/GHSA-mcph-m25j-8j63
=> Update changed-files action to v45

slices/ca-certificates-java.yaml, slices/libnss3.yaml, slices/openjdk-8-jre-headless.yaml
This PR restructures the libnss3 slices. It renames the former `libs` slice to `nss`, to only include nss3-specific libraries. It also adds a new slice `smime` to include S/MIME libraries.
Finally, the `libs` slice is added back, which includes all of the slices that provide libraries. The rationale is that "libs" slices should contain all libraries coming from the package.
Note that the ca-certificates-java slice has also been updated to reflect this change.
Resolves #381
=> fix(22.04/libnss3): libs should contain all libraries

slices/librdkafka++1.yaml, slices/librdkafka1.yaml
Add SDF for the `librdkafka++1` package and dependencies
* 24.04 PR: #399
Notable difference: `librdkafka` has a new dependency on `libcurl4t64` in 24.10 that it did not have in 24.04
=> feat(24.10): Add SDF for `librdkafka++1`

slices/libgflags2.2.yaml, slices/librocksdb8.9.yaml, slices/libsnappy1v5.yaml
Add SDF for the `librocksdb8.9` package and dependencies
* 24.10 PR: #400
Notable difference: package is `librocksdb8.9` on 24.04 and `librocksdb9.3` on 24.10, SDF are otherwise similar
=> feat(24.04): Add SDF for `librocksdb8.9` and dependencies

slices/libgflags2.2.yaml, slices/librocksdb9.3.yaml, slices/libsnappy1v5.yaml
Add SDF for the `librocksdb9.3` package and dependencies
* 24.04 PR: #401
Notable difference: package is `librocksdb8.9` on 24.04 and `librocksdb9.3` on 24.10, SDF are otherwise similar
=> feat(24.10): Add SDF for `librocksdb9.3` and dependencies

chisel.yaml
This PR adds the Ubuntu Pro archive definitions for Jammy (22.04).
The `pro` and `priority` values are defined in the [RK018 spec](https://docs.google.com/document/d/1nN5UuhwpGD9b07AaYA2RxMEwN1LT8MYQyC1Lg5zlrxg/edit?tab=t.0).
=> feat(22.04): add pro archives definition

slices/libnginx-mod-http-headers-more-filter.yaml, slices/nginx.yaml, tests/spread/integration/libnginx-mod-http-headers-more-filter/task.yaml
feat(24.10): add slice for libnginx-mod-http-headers-more-filter
#437
```shell
$ chisel cut --release chisel-releases/ --root foo base-files_var base-passwd_data libnginx-mod-http-headers-more-filter_modules
2024/12/17 03:41:20 Processing chisel-releases/ release...
2024/12/17 03:41:26 Selecting slices...
2024/12/17 03:41:26 Fetching ubuntu 24.10 oracular suite details...
2024/12/17 03:41:27 Release date: Fri, 11 Oct 2024 10:20:59 UTC
2024/12/17 03:41:27 Fetching index for ubuntu 24.10 oracular main component...
2024/12/17 03:41:27 Fetching index for ubuntu 24.10 oracular universe component...
2024/12/17 03:41:27 Fetching ubuntu 24.10 oracular-security suite details... …
```
=> feat(24.10): add slice for libnginx-mod-http-headers-more-filter

slices/libtheora0.yaml, slices/libx11-xcb1.yaml
Add SDF for `libtheora0` and `libx11-xcb1`
* 24.10: #432
=> feat(24.04): Add SDF for `libtheora0` and `libx11-xcb1`

slices/libtheora0.yaml, slices/libx11-xcb1.yaml
Add SDF for `libtheora0` and `libx11-xcb1`
* 24.04: #433
=> feat(24.10): Add SDF for `libtheora0` and `libx11-xcb1`

slices/aspnetcore-runtime-9.0.yaml, slices/dotnet-host-9.0.yaml, slices/dotnet-hostfxr-9.0.yaml, slices/dotnet-runtime-9.0.yaml, tests/spread/integration/aspnetcore-runtime-9.0/task.yaml, tests/spread/integration/aspnetcore-runtime-9.0/web_helloworld/Hello.csproj, tests/spread/integration/aspnetcore-runtime-9.0/web_helloworld/Program.cs, tests/spread/integration/aspnetcore-runtime-9.0/web_helloworld/Properties/launchSettings.json, tests/spread/integration/aspnetcore-runtime-9.0/web_helloworld/appsettings.Development.json, tests/spread/integration/aspnetcore-runtime-9.0/web_helloworld/appsettings.json, tests/spread/integration/dotnet-host-9.0/task.yaml, tests/spread/integration/dotnet-runtime-9.0/app_helloworld/Hello.csproj, tests/spread/integration/dotnet-runtime-9.0/app_helloworld/Program.cs, tests/spread/integration/dotnet-runtime-9.0/task.yaml
This PR add the slice definitions for .NET9 packages. 
* For the current `chisel` implementation, conflicts with .NET8 packages are worked around with `/usr/lib/dotnet/dotnet9: {copy: /usr/lib/dotnet/dotnet}`.
Not applicable.
=> feat(24.10): add .NET9 slices

slices/geoip-bin.yaml, slices/geoip-database.yaml, slices/geoipupdate.yaml, slices/libgeoip1t64.yaml, slices/libmaxminddb0.yaml, slices/libnginx-mod-http-geoip.yaml, slices/libnginx-mod-http-geoip2.yaml, slices/libnginx-mod-stream-geoip.yaml, slices/libnginx-mod-stream-geoip2.yaml, slices/libnginx-mod-stream.yaml, slices/mmdb-bin.yaml, tests/spread/integration/geoip-bin/task.yaml, tests/spread/integration/geoipupdate/task.yaml, tests/spread/integration/libnginx-mod-http-geoip/task.yaml, tests/spread/integration/libnginx-mod-http-geoip2/task.yaml, tests/spread/integration/libnginx-mod-stream-geoip/task.yaml, tests/spread/integration/libnginx-mod-stream-geoip2/task.yaml, tests/spread/integration/libnginx-mod-stream/task.yaml, tests/spread/integration/mmdb-bin/task.yaml
feat(24.04): add slices for NGINX GeoIP modules and dependencies
#440
```shell
$ chisel cut --release chisel-releases/ --root foo geoip-bin_bins
2024/12/17 08:12:51 Processing chisel-releases/ release...
2024/12/17 08:13:05 Selecting slices...
2024/12/17 08:13:05 Fetching ubuntu 24.04 noble suite details...
2024/12/17 08:13:06 Release date: Thu, 25 Apr 2024 15:10:33 UTC
2024/12/17 08:13:06 Fetching index for ubuntu 24.04 noble main component...
2024/12/17 08:13:06 Fetching index for ubuntu 24.04 noble universe component...
2024/12/17 08:13:06 Fetching ubuntu 24.04 noble-security suite details...
2024/12/17 08:13:06 Release date: Tue, 17 Dec 2024 11:34:42 UTC
2024/12/17 …
```
=> feat(24.04): add slices for NGINX GeoIP modules and dependencies

slices/geoip-bin.yaml, slices/geoip-database.yaml, slices/geoipupdate.yaml, slices/libgeoip1t64.yaml, slices/libmaxminddb0.yaml, slices/libnginx-mod-http-geoip.yaml, slices/libnginx-mod-http-geoip2.yaml, slices/libnginx-mod-stream-geoip.yaml, slices/libnginx-mod-stream-geoip2.yaml, slices/libnginx-mod-stream.yaml, slices/mmdb-bin.yaml, tests/spread/integration/geoip-bin/task.yaml, tests/spread/integration/geoipupdate/task.yaml, tests/spread/integration/libnginx-mod-http-geoip/task.yaml, tests/spread/integration/libnginx-mod-http-geoip2/task.yaml, tests/spread/integration/libnginx-mod-stream-geoip/task.yaml, tests/spread/integration/libnginx-mod-stream-geoip2/task.yaml, tests/spread/integration/libnginx-mod-stream/task.yaml, tests/spread/integration/mmdb-bin/task.yaml
feat(24.10): add slices for NGINX GeoIP modules and dependencies
#439
```shell
$ chisel cut --release chisel-releases/ --root foo geoip-bin_bins
2024/12/17 08:32:51 Processing chisel-releases/ release...
2024/12/17 08:32:57 Selecting slices...
2024/12/17 08:32:57 Fetching ubuntu 24.10 oracular suite details...
2024/12/17 08:32:57 Release date: Fri, 11 Oct 2024 10:20:59 UTC
2024/12/17 08:32:57 Fetching index for ubuntu 24.10 oracular main component...
2024/12/17 08:32:57 Fetching index for ubuntu 24.10 oracular universe component...
2024/12/17 08:32:57 Fetching ubuntu 24.10 oracular-security suite details...
2024/12/17 08:32:58 Release date: Tue, 17 Dec 2024 11:34:07 UTC …
```
=> feat(24.10): add slices for NGINX GeoIP modules and dependencies

slices/iputils-ping.yaml, tests/spread/integration/iputils-ping/task.yaml
feat(24.04): add SDF for iputils-ping
=> feat(24.04): add SDF for iputils-ping

slices/gearman-job-server.yaml, slices/gearman-tools.yaml, slices/libboost-program-options1.83.0.yaml, slices/libevent-2.1-7t64.yaml, slices/libevent-core-2.1-7t64.yaml, slices/libevent-pthreads-2.1-7t64.yaml, slices/libgearman8t64.yaml, slices/libhashkit2t64.yaml, slices/libhiredis1.1.0.yaml, slices/libmemcached11t64.yaml, slices/libmysqlclient21.yaml, slices/mysql-common.yaml, tests/spread/integration/gearman-job-server/task.yaml, tests/spread/integration/gearman-tools/task.yaml
feat(24.04): add slices for Gearman and dependencies
#444 
=> feat(24.04): add slices for Gearman and dependencies

slices/libarchive-tools.yaml, slices/libarchive13t64.yaml, tests/spread/integration/libarchive-tools/task.yaml
feat(24.04): add SDF for libarchive-tools and dependencies
#456 
=> feat(24.04): add SDF for libarchive-tools and dependencies

slices/libavcodec60.yaml, slices/libavutil58.yaml, slices/libcairo-gobject2.yaml, slices/libhwy1t64.yaml, slices/libjxl0.7.yaml, slices/librsvg2-2.yaml, slices/libsoxr0.yaml, slices/libswresample4.yaml, slices/libva-x11-2.yaml, slices/libvdpau1.yaml, slices/libvpl2.yaml, slices/libxfixes3.yaml
Add SDF for `libavcodec60` and dependencies.
See https://github.com/canonical/chisel/issues/93#issuecomment-2562008596 for the dependencies diff.
24.10 PR: #442
=> feat(24.04): Add SDF for `libavcodec60` and dependencies

slices/libavcodec61.yaml, slices/libavutil59.yaml, slices/libcairo-gobject2.yaml, slices/libgdk-pixbuf-2.0-0.yaml, slices/libgdk-pixbuf2.0-common.yaml, slices/libhwy1t64.yaml, slices/libjxl0.10.yaml, slices/librsvg2-2.yaml, slices/libsoxr0.yaml, slices/libswresample5.yaml, slices/libva-x11-2.yaml, slices/libvdpau1.yaml, slices/libvpl2.yaml, slices/libxfixes3.yaml, slices/shared-mime-info.yaml, tests/spread/integration/libgdk-pixbuf-2.0-0/task.yaml, tests/spread/integration/shared-mime-info/task.yaml
Add SDF for `libavcodec61` and dependencies.
See https://github.com/canonical/chisel/issues/93#issuecomment-2562008596 for the dependencies diff.
24.04 PR: #441
=> feat(24.10): Add SDF for `libavcodec61` and dependencies

slices/libavformat61.yaml, slices/libdvdnav4.yaml, slices/libdvdread8t64.yaml, slices/libgme0.yaml, slices/librabbitmq4.yaml, slices/librist4.yaml, slices/libsrt1.5-gnutls.yaml, slices/libssh-gcrypt-4.yaml
Add SDF for `libavformat61` and dependencies.
24.04 PR: #468
=> feat(24.10): Add SDF for `libavformat61` and dependencies

slices/liblilv-0-0.yaml, slices/libsord-0-0.yaml, slices/libsratom-0-0.yaml
Add SDF for `liblilv-0-0` and dependencies.
24.04 PR: #469
=> feat(24.10): Add SDF for `liblilv-0-0` and dependencies

slices/liblilv-0-0.yaml, slices/libsord-0-0.yaml, slices/libsratom-0-0.yaml
Add SDF for `liblilv-0-0` and dependencies.
24.10 PR: #470
=> feat(24.04): Add SDF for `liblilv-0-0` and dependencies

slices/libavformat60.yaml, slices/libgme0.yaml, slices/librabbitmq4.yaml, slices/librist4.yaml, slices/libsrt1.5-gnutls.yaml, slices/libssh-gcrypt-4.yaml
Add SDF for `libavformat60` and dependencies.
24.10 PR: #471
=> feat(24.04): Add SDF for `libavformat60` and dependencies

slices/libduktape207.yaml, slices/libproxy1v5.yaml, slices/publicsuffix.yaml
Port forward of #389  
Rework of #49, as it has not been updated in a while.
This PD adds the following changes:
- The data slice in `publicsuffix` is more explicit following earlier comments in #49 
- `glib-networking` and dependent `gsettings-desktop-schemas` were removed. Since these packages related to the gnome desktop environment, I am hesitant to add them unless they can be tested in a minimal rootfs. 
=> feat(24.10): add publicsuffix and libproxy1v5 slices

slices/aspnetcore-runtime-9.0.yaml
Fix third party notices filepath in `aspnetcore-runtime-9.0_notice` slice.
Currently running `chisel cut --release ubuntu-24.10 --root rootfs aspnetcore-runtime-9.0_notice` yields the following error:
```
error: cannot extract from package "aspnetcore-runtime-9.0": no content at /usr/lib/dotnet/shared/Microsoft.AspNetCore.App/9.0.0/THIRD-PARTY-NOTICES.txt
```
This is because that file is at `/usr/lib/dotnet/shared/Microsoft.AspNetCore.App/9.0.1/THIRD-PARTY-NOTICES.txt` on amd64 and other `rc` version paths for other archs, for example `/usr/lib/dotnet/shared/Microsoft.AspNetCore.App/9.0.0-rc.1.24452.1/THIRD-PARTY-NOTICES.txt` for arm64, see https://packages.ubuntu.com/oracular/aspnetcore-runtime-9.0.
This currently causes all 24.10 "Install slices" CI workflow runs to fail: …
=> fix(24.10): Fix notices file path in `aspnetcore-runtime-9.0_notice` slice

slices/less.yaml, tests/spread/integration/less/task.yaml
Add `less`
Dependent by #331 
Will open once approved.
=> feat(24.04): add less

.github/workflows/cla-check.yaml
Following the conversations on Mattermost, let's bump the [Has Signed Canonical CLA](https://github.com/marketplace/actions/has-signed-canonical-cla) action to v2.
=> ci: bump canonical/has-signed-canonical-cla to v2

slices/ca-certificates-java.yaml, tests/spread/integration/ca-certificates-java/task.yaml
Forward port ca-certificates-java slice that was missed in forward porting openjdk-8 slices.
[Ubuntu 24.04](https://github.com/canonical/chisel-releases/pull/308)
=> chore(24.10): forward-port ca-certificates-java slice from ubuntu 24.04

slices/libnss-extrausers.yaml, slices/libnss-mdns.yaml
Add libnss extra libraries like extrausers and mdns:
* extrausers does not exist on i386
=> feat(24.04): add libnss-{extrausers,mdns}

slices/libnss-extrausers.yaml, slices/libnss-mdns.yaml
Forward port from https://github.com/canonical/chisel-releases/pull/345
=> feat(24.10): port libnss-extra-mdns to 24.10

slices/vim-common.yaml, slices/vim-tiny.yaml, tests/spread/integration/vim-tiny/task.yaml
feat(24.04): add SDF for vim.tiny
#491 
=> feat(24.04): add SDF for vim.tiny

.github/workflows/spread.yaml
Execution of arm64 github runners on forked branches was disabled due to a recently found attack vector.
We have temporarily disabled arm64 spread tests from the CI matrix to keep development going. This change needs to be reverted in ~2wks when the runner restrictions are lifted
=> Rocks-1890/temporarily disable arm tests

slices/openjdk-21-jdk-headless.yaml, slices/openjdk-21-jre-headless.yaml, tests/spread/integration/openjdk-11-jdk-headless/task.yaml, tests/spread/integration/openjdk-11-jre-headless/task.yaml, tests/spread/integration/openjdk-17-jdk-headless/task.yaml, tests/spread/integration/openjdk-17-jre-headless/task.yaml, tests/spread/integration/openjdk-21-jdk-headless/Main.java, tests/spread/integration/openjdk-21-jdk-headless/MonitoringTest.java, tests/spread/integration/openjdk-21-jdk-headless/SerializableObject.java, tests/spread/integration/openjdk-21-jdk-headless/task.yaml, tests/spread/integration/openjdk-21-jre-headless/ConsoleTest.java, tests/spread/integration/openjdk-21-jre-headless/Main.java, tests/spread/integration/openjdk-21-jre-headless/PrefsTest.java, tests/spread/integration/openjdk-21-jre-headless/ReadCertificate.java, tests/spread/integration/openjdk-21-jre-headless/TestJMX.java, tests/spread/integration/openjdk-21-jre-headless/TestJMXMBean.java, tests/spread/integration/openjdk-21-jre-headless/task.yaml
This PR forward-ports openjdk-21 slices from ubuntu 24.04
[ubuntu 24.04](https://github.com/canonical/chisel-releases/pull/313)
=> chore(24.10): forward port openjdk-21 slices from ubuntu24.04

slices/vim-common.yaml, slices/vim-tiny.yaml, tests/spread/integration/vim-tiny/task.yaml
feat(24.10): add SDF for vim.tiny
#490 
=> feat(24.10): add SDF for vim.tiny

slices/libgbm1.yaml, slices/libgl1-mesa-dri.yaml, slices/libgl1.yaml, slices/libglapi-mesa.yaml, slices/libglvnd0.yaml, slices/libglx-mesa0.yaml, slices/libglx0.yaml, slices/libllvm19.yaml, slices/libsensors-config.yaml, slices/libsensors5.yaml, slices/libvulkan1.yaml, slices/libwayland-server0.yaml, slices/libxxf86vm1.yaml, slices/mesa-libgallium.yaml
This PR backports the changes for `libgl1` from #475. There is an existing PR for noble, however this PR is consistent with the dependencies from noble-updates archive which differ significantly from the noble archive alone.
=> feat(24.04): slices for libgl1

slices/libgbm1.yaml, slices/libgl1-mesa-dri.yaml, slices/libgl1.yaml, slices/libglapi-mesa.yaml, slices/libglvnd0.yaml, slices/libglx-mesa0.yaml, slices/libglx0.yaml, slices/libllvm19.yaml, slices/libsensors-config.yaml, slices/libsensors5.yaml, slices/libvulkan1.yaml, slices/libwayland-server0.yaml, slices/libxxf86vm1.yaml, slices/mesa-libgallium.yaml
Add SDF for `libgl1` and dependencies.
See https://github.com/canonical/chisel/issues/93 for the dependency diff.
24.04 PR: #474 (dropped)
24.04 PR: #508 (current, back-ported)
N/A
=> feat(24.10): Add SDF for `libgl1` and dependencies

.github/workflows/spread.yaml
The ARM runners appear to be available again. Let's re-enable them again in tests
=> Revert "Rocks-1890/temporarily disable arm tests"

.github/workflows/spread.yaml
Address https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/ by pinning the action to a known safe sha.
=> fix(ci): address CVE-2025-30066

slices/openjdk-21-jdk-headless.yaml, slices/openjdk-21-jre-headless.yaml, tests/spread/integration/openjdk-21-jdk-headless/Main.java, tests/spread/integration/openjdk-21-jdk-headless/MonitoringTest.java, tests/spread/integration/openjdk-21-jdk-headless/SerializableObject.java, tests/spread/integration/openjdk-21-jdk-headless/task.yaml, tests/spread/integration/openjdk-21-jre-headless/ConsoleTest.java, tests/spread/integration/openjdk-21-jre-headless/Main.java, tests/spread/integration/openjdk-21-jre-headless/PrefsTest.java, tests/spread/integration/openjdk-21-jre-headless/ReadCertificate.java, tests/spread/integration/openjdk-21-jre-headless/TestJMX.java, tests/spread/integration/openjdk-21-jre-headless/TestJMXMBean.java, tests/spread/integration/openjdk-21-jre-headless/task.yaml
Backport  openjdk-21 chisel slices
https://github.com/canonical/chisel-releases/pull/313
https://github.com/canonical/chisel-releases/pull/363 
n/a (present in 24.04)
=> feat(22.04): backport openjdk-21 slices from 24.04

slices/libnss3.yaml, slices/openjdk-21-jdk-headless.yaml, slices/openjdk-21-jre-headless.yaml, tests/spread/integration/openjdk-21-jdk-headless/Main.java, tests/spread/integration/openjdk-21-jdk-headless/MonitoringTest.java, tests/spread/integration/openjdk-21-jdk-headless/SerializableObject.java, tests/spread/integration/openjdk-21-jdk-headless/task.yaml, tests/spread/integration/openjdk-21-jre-headless/ConsoleTest.java, tests/spread/integration/openjdk-21-jre-headless/Main.java, tests/spread/integration/openjdk-21-jre-headless/PrefsTest.java, tests/spread/integration/openjdk-21-jre-headless/ReadCertificate.java, tests/spread/integration/openjdk-21-jre-headless/TestJMX.java, tests/spread/integration/openjdk-21-jre-headless/TestJMXMBean.java, tests/spread/integration/openjdk-21-jre-headless/task.yaml
This PR backports openjdk-21 slices to focal.
https://github.com/canonical/chisel-releases/pull/395
https://github.com/canonical/chisel-releases/pull/313
https://github.com/canonical/chisel-releases/pull/363
https://github.com/canonical/chisel-releases/pull/516
=> feat(20.04): backport openjdk 21 slices from 24.04

.github/scripts/install-slices/version-matrix.py, .github/workflows/install-slices.yaml
This commit adds another dimension of testing for the CI. Now we can specify Chisel versions that should be tested against a branch. This is necessary to make sure we maintain backwards compatibility with complex features such as hard link support.
Internal Jira ticket.
N/A
Example run:
* Push on main: https://github.com/letFunny/chisel-releases/actions/runs/13590801595/job/37996227785
* On pull request: https://github.com/letFunny/chisel-releases/actions/runs/13627359023/job/38087361799
> [!CAUTION]
> After we change this PR to incorporate the feedback I will run the workflows again to make sure they still works. Github actions are rather flaky, especially in regards …
=> feat: compatibility matrix CI for Chisel versions

slices/openssl.yaml
The OpenSSL copyright is a symlink to libssl's, so this PR adds that dependency.
=> fix(openssl): copyright depends on libssl copyright - oracular

slices/openssl.yaml
See https://github.com/canonical/chisel-releases/pull/524/files
=> fix(openssl): copyright depends on libssl copyright - focal

slices/openssl.yaml
See https://github.com/canonical/chisel-releases/pull/523
=> fix(openssl): copyright depends on libssl copyright - jammy

slices/openssl.yaml
See https://github.com/canonical/chisel-releases/pull/522
=> fix(openssl): copyright depends on libssl copyright - noble

.github/workflows/spread.yaml
- Allow dynamic selection of Github runners based on repository owner. This allows forks of chisel-releases to run both AMD64 and ARM64 spread tests.
- Forked repo scenario: https://github.com/clay-lake/chisel-releases/actions/runs/14617501925?pr=4
- Upstream repo scenario: https://github.com/clay-lake/chisel-releases/actions/runs/14617501925/job/41071341853?pr=4
- Note: This is "simulated" canonical environment and will fail since we cannot satisfy the canonical hosted runner labels on my fork
=> feat: dynamic runner selection

.github/workflows/install-slices.yaml
- When testing specific branches, swap the ref in the RELEASE JSON with the current feature branch to be merged in
This should fix the instability tests we are currently seeing.
=> Fix: Inject correct ref for testing feature branches

.github/workflows/install-slices.yaml
- This is a correction to the prior PR #526 to enable installability test across chisel-release forks.
Sample Execution: https://github.com/clay-lake/chisel-releases/pull/5
=> Fix: Clear ref in installability matrix for pull requests

spread.yaml
- Execute `apt-get update` on allocation of lxc instances for spread tests. This fixes errors found in integration tests while configuring the test environment.
See: #521 and https://github.com/canonical/chisel-releases/actions/runs/14645651222/job/41113484419#step:10:193
=> Fix(24.10): Include apt-get update in LXC allocation

spread.yaml
- Execute `apt-get update` on allocation of lxc instances for spread tests. This fixes errors found in integration tests while configuring the test environment.
See: #521 and https://github.com/canonical/chisel-releases/actions/runs/14645651222/job/41113484419#step:10:193
=> Fix(24.04): Include apt-get update in LXC allocation

spread.yaml
- Execute `apt-get update` on allocation of lxc instances for spread tests. This fixes errors found in integration tests while configuring the test environment.
See: #521 and https://github.com/canonical/chisel-releases/actions/runs/14645651222/job/41113484419#step:10:193
=> Fix(20.04): Include apt-get update in LXC allocation

spread.yaml
- Execute `apt-get update` on allocation of lxc instances for spread tests. This fixes errors found in integration tests while configuring the test environment.
See: #521 and https://github.com/canonical/chisel-releases/actions/runs/14645651222/job/41113484419#step:10:193
=> Fix(22.04): Include apt-get update in LXC allocation

.github/workflows/lint.yaml
The lint workflow currently produces a ton of warnings for slices names not being sorted. In practice, we do not abide by that rule much and it's tough to find the actual errors within the sea of warnings. This PR disables emitting those warnings.
=> ci(lint): do not produce warnings

.github/workflows/ci-pr-target.yaml, .github/workflows/ci.yaml
- Revert modifications made for testing `ubuntu-25.04` on my fork back to their original state.
=> Feat(25.04): Revert to `canonical` CI

README.md
- Update the README.md in `main` to reflect new ubuntu-25.04 release.
=> Feat(25.04): Update README on main

.github/workflows/triage-prs.yaml
On every PR, this new workflow will auto-request the canonical/slice-reviewers-guild team to review it.
Test: https://github.com/cjdcordeiro-new-test/ci-playground/pull/11
=> ci: add workflow for auto-requesting reviews

slices/base-files.yaml
-  Uncomment the base-files_chisel slice which was disabled during the release of 25.04.
=> fix(25.04): Uncomment Chisel Manifest Generation Slice

slices/systemd.yaml, tests/spread/integration/systemd/task.yaml, tests/spread/integration/systemd/test.sh
- Portforward of systemd from `ubuntu-24.04`
**Note: These changes need a close second review. The current test coverage is not sufficient entirely certain these changes are correct**
- [slices/systemd.yaml](https://pastebin.ubuntu.com/p/SQKMdbtPhW/)
=> feat(25.04): systemd portforward

README.md
This line was unintentionally removed in https://github.com/canonical/chisel-releases/pull/595 and flagged in https://github.com/canonical/chisel-releases/commit/5a7652a8b6f0ff674aa43bb60718a7a2eee593a7#r162272346
We should preserver EOL chisel-releases and mark them as such.
https://github.com/canonical/chisel-releases/pull/595
=> fix(README): keep 24.10 ref as EOL

slices/coreutils.yaml, slices/libssl3t64.yaml, tests/spread/integration/coreutils/task.yaml
As discussed in #592, the `coreutils_bins` slice is bringing in a lot of binaries which are not necessarily needed on per-use basis. This PR adds coreuitls subslices to use in the php 8.3 slices (see below for how these were determined).
25.04: #606
The php shell scripts in question are in the `php-common` slice. some are in `usr/sbin` and some others in `usr/lib/php`
```
/usr/sbin/phpdismod -> phpenmod (symlink)
/usr/sbin/phpenmod
/usr/sbin/phpquery
/usr/lib/php/php-fpm-socket-helper
/usr/lib/php/php-helper
/usr/lib/php/php-maintscript-helper
/usr/lib/php/sessionclean
```
The candidates have been triaged with the following script:
```bash
#!/bin/bash
BINS="\[ arch …
```
=> feat(24.04) subslice coreutils for php

slices/coreutils.yaml, tests/spread/integration/coreutils/smoke.sh, tests/spread/integration/coreutils/task.yaml
Forward port of #605. coreutils in plucky seems to have already been sliced into groups according to the [GNU coreutils manual](https://www.gnu.org/software/coreutils/manual/html_node/index.html) chapter headings. I've added the single-binary slices as well as the tests, in the same format as in the noble pr.
Note:
- i *have* gone through the bash script dependencies of the php 2.96 in plucky again, just to be sure. they are the same.
- `sort` in plucky, unlike in noble, does *not* depend on `libssl3t64`
N/A
=> feat(25.04) subslice coreutils for php

.github/workflows/triage-prs.yaml
The triaging of PRs has only been running for `main`, because it relied on `pull_request_target` events, which very much like `pull_request`, only works if the workflow exists in the PR's base branch.
This fix makes the wf run on a schedule, adding the reviewers where they haven't been requested yet.
Tested in https://github.com/cjdcordeiro/ci-playground/actions/runs/16298445252
=> fix(ci): PR triaging needs to happen on schedule

slices/debianutils.yaml, slices/gzip.yaml, slices/util-linux.yaml, tests/spread/integration/debianutils/task.yaml, tests/spread/integration/gzip/task.yaml
This is a back-porting PR from 25.04 for gzip and debianutils.
#629
#629 
The contents in `slices/gzip.yaml` and `tests/spread/integration/gzip/task.yaml` reference the dropped PR https://github.com/canonical/chisel-releases/pull/331
=> feat(24.04): add gzip and debianutils

chisel.yaml
add `maintenance` field to chisel.yaml
dates obtained with:
```
date -d "today + $(distro-info --days=release --series <series>) days" --iso-8601 
```
[distro-info data](https://git.launchpad.net/ubuntu/+source/distro-info-data/plain/ubuntu.csv)
implements #631, resolves #675
25.10: #681
25.04: #680
24.04: #679 **(this pr)** 
22.04: #678
20:04: #677
=> feat(24.04): add maintenance to chisel.yaml

slices/gearman-job-server.yaml, slices/gearman-tools.yaml, slices/libboost-program-options1.88.0.yaml
The gearman packages on questing got updated to a newer version of libboost-program-options. The older one still exists and is used by many apps, so I added a copy of those slices (checking that they're still correct) for the newer version and updated the gearman slices.
n/a
n/a
=> fix(25.10): update gearman dependencies

slices/openssh-client.yaml, tests/spread/integration/openssh-client/task.yaml, tests/spread/integration/openssh-client/test_bins.sh, tests/spread/integration/openssh-client/test_ssh-argv0.sh, tests/spread/integration/openssh-client/test_ssh-copy-id.sh
This updates the openssh slices for the removal of:
- /usr/bin/slogin
- /usr/lib/openssh/agent-launch
It also adds integration tests.
While writing the integration tests, I noticed that ssh-copy-id and ssh-argv0 are actually shell scripts, so I separated them into their own slices and made a scripts slice for them and added their appropriate dependencies. These dependencies are notably absent from the actual openssh-client package, which may be a packaging bug. The individual slices are useful for distinguishing which slices are necessary for which script.
Fixes #653 
n/a
We may want to backport the scripts slice to earlier releases, but I'm unsure how best to do that …
=> fix(25.10): update openssh-client slices for openssh 10.0

slices/base-files.yaml
Installing gdb in the dev rock does not work because /etc/profile.d is missing:
```
2025-10-01 14:11:25.811 :: #5 175.5 Use of uninitialized value $Debconf::Encoding::charmap in scalar chomp at /usr/share/perl5/Debconf/Encoding.pm line 17.
2025-10-01 14:11:25.811 :: #5 175.6 ln: failed to create symbolic link '/etc/profile.d/debuginfod.sh': No such file or directory
2025-10-01 14:11:25.811 :: #5 175.6 dpkg: error processing package libdebuginfod-common (--configure):
2025-10-01 14:11:25.811 :: #5 175.6  installed libdebuginfod-common package post-installation script subprocess returned error exit status 1
```
https://github.com/canonical/chisel-releases/pull/686
https://github.com/canonical/chisel-releases/pull/687 …
=> fix(24.04): base-files_etc - add /etc/profile.d
