canonical/chisel-releases

slices/dotnet-runtime-6.0.yaml, slices/liblzma5.yaml, slices/libunwind-13.yaml, slices/libunwind8.yaml
Also add it as dependency to dotnet-runtime-6.0.
=> Add new libunwind8

slices/libharfbuzz0b.yaml
This adds the text shaping engine Harfbuzz https://packages.ubuntu.com/jammy/libharfbuzz0b
=> [22.04] Add slice for libharfbuzz0b

slices/libdb5.3.yaml, slices/libgmp10.yaml, slices/libgnutls30.yaml, slices/libhogweed6.yaml, slices/libidn2-0.yaml, slices/libldap-2.5-0.yaml, slices/libnettle8.yaml, slices/libp11-kit0.yaml, slices/libsasl2-2.yaml, slices/libsasl2-modules-db.yaml, slices/libtasn1-6.yaml, slices/libunistring2.yaml
Adds slices for ldap and dependencies.
=> Adding slices for libldap-2.5 and dependencies

slices/libasan6.yaml
Add slice for [libasan6](https://packages.ubuntu.com/focal/libasan6)
=> [22.04] Add libasan6

slices/libgomp1.yaml
Add [libgomp1](https://packages.ubuntu.com/jammy/libgomp1) slice
=> [22.04] Add libgomp1

slices/aspnetcore-runtime-8.0.yaml, slices/dotnet-host-8.0.yaml, slices/dotnet-hostfxr-8.0.yaml, slices/dotnet-runtime-8.0.yaml
This is a duplicate of https://github.com/canonical/chisel-releases/pull/70, since I didn't have the rights to rebase that PR.
Closes https://github.com/canonical/chisel-releases/pull/70
=> feat: add slices for dotnet8

slices/bash.yaml, slices/coreutils.yaml, slices/libacl1.yaml, slices/libattr1.yaml, slices/libgmp10.yaml, slices/libpcre2-8-0.yaml, slices/libselinux1.yaml, slices/libtinfo6.yaml
The changes are mostly from https://github.com/canonical/chisel-releases/pull/61, for ubuntu-24.04.
=> feat(24.04): add slices for bash and coreutils

slices/bash.yaml, slices/coreutils.yaml, slices/libacl1.yaml, slices/libattr1.yaml, slices/libgmp10.yaml, slices/libtinfo6.yaml
The changes are mostly from https://github.com/canonical/chisel-releases/pull/61, for ubuntu-23.10.
=> feat(23.10): add slices for bash and coreutils

slices/bash.yaml, slices/coreutils.yaml, slices/libacl1.yaml, slices/libattr1.yaml, slices/libgmp10.yaml, slices/libpcre2-8-0.yaml, slices/libselinux1.yaml, slices/libtinfo6.yaml
The changes are mostly from #61, for ubuntu-23.04.
=> feat(23.04): add slices for bash and coreutils

slices/dash.yaml
cherry pick of https://github.com/canonical/chisel-releases/pull/84
=> add dash package for ubuntu 24.04

slices/tzdata.yaml
This PR adds the tzdata slices for 24.04.
---
:yellow_circle: Changes are same in #91.
=> feat(24.04): add tzdata slices

slices/gawk.yaml, slices/libmpfr6.yaml, slices/libsigsegv2.yaml
Adds 23.10 slices for:
1. gawk
2. libmpfr6
3. libsigsegv2
See #106 for review details
=> feat(23.10) add slices for (g)awk and dependencies

slices/gawk.yaml, slices/libmpfr6.yaml, slices/libsigsegv2.yaml
Adds 24.04 slices for:
1. gawk
2. libmpfr6
3. libsigsegv2
See #106 for review details
=> feat(24.04): add slices for (g)awk and dependencies

.github/workflows/ci.yaml
This PR adds a workflow to test installing changed or all slices, based on the files changed.
---
Equivalent of #120.
=> chore(20.04): add workflow to test slices

.github/workflows/ci.yaml
Add the CLA checks for the 22.04 branch.
https://github.com/canonical/chisel-releases/pull/165
https://github.com/canonical/chisel-releases/pull/165
Worked on https://github.com/canonical/chisel-releases/pull/132 - https://github.com/canonical/chisel-releases/actions/runs/8083045516
=> ci(cla-check): add CLA check for ubuntu-22.04

.github/workflows/ci.yaml
Add the CLA checks for the 23.10 branch.
https://github.com/canonical/chisel-releases/pull/165
Worked on https://github.com/canonical/chisel-releases/pull/132 - https://github.com/canonical/chisel-releases/actions/runs/8083045516
=> ci(cla-check): add CLA check for ubuntu-23.10

.github/workflows/ci.yaml
Add the CLA checks for the 24.04 branch.
Worked on #132 - https://github.com/canonical/chisel-releases/actions/runs/8083045516
=> ci(cla-check): add CLA check for ubuntu-24.04

slices/dash.yaml
feat(20.04): add slice for dash
#155
824e5d19de3aa7932d0fe6df112b87f948b55978
67add29c28914e7980d0340b22462c1c1416098f
```bash
$ chisel cut --release chisel-releases/ --root foo dash_bins        
2024/02/29 10:22:12 Processing chisel-releases/ release...
2024/02/29 10:22:12 Selecting slices...
2024/02/29 10:22:12 Fetching ubuntu 20.04 focal suite details...
2024/02/29 10:22:12 Release date: Thu, 23 Apr 2020 17:33:17 UTC
2024/02/29 10:22:12 Fetching index for ubuntu 20.04 focal main component...
2024/02/29 10:22:12 Fetching index for ubuntu 20.04 focal universe component...
2024/02/29 10:22:12 Fetching ubuntu 20.04 focal-security suite details...
2024/02/29 10:22:12 Release date: Thu, 29 Feb 2024 12:12:56 UTC
2024/02/29 10:22:12 Fetching index for ubuntu 20.04 focal-security main …
```
=> feat(20.04): add slice for dash

slices/libc-bin.yaml
feat(24.04): add slice for libc-bin
#155
d3c1f481ea560df01a89fa589a89d01e770ff5b8
```bash
$ chisel cut --release chisel-releases/ --root foo libc-bin_nsswitch           
2024/02/29 10:16:37 Processing chisel-releases/ release...
2024/02/29 10:16:38 Selecting slices...
2024/02/29 10:16:38 Fetching ubuntu 24.04 noble suite details...
2024/02/29 10:16:38 Release date: Thu, 29 Feb 2024 15:03:37 UTC
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble main component...
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble universe component...
2024/02/29 10:16:38 Fetching ubuntu 24.04 noble-security suite details...
2024/02/29 10:16:38 Release date: Thu, 04 Jan 2024 18:43:12 UTC
2024/02/29 10:16:38 Fetching index for ubuntu 24.04 noble-security main component...
2024/02/29 10:16:38 …
```
=> feat(24.04): add slice for libc-bin

slices/libc-bin.yaml
feat(20.04): add slice for libc-bin
#155
d3c1f481ea560df01a89fa589a89d01e770ff5b8
```bash
$ chisel cut --release chisel-releases/ --root foo libc-bin_nsswitch
2024/02/29 10:18:58 Processing chisel-releases/ release...
2024/02/29 10:18:58 Selecting slices...
2024/02/29 10:18:58 Fetching ubuntu 20.04 focal suite details...
2024/02/29 10:18:59 Release date: Thu, 23 Apr 2020 17:33:17 UTC
2024/02/29 10:18:59 Fetching index for ubuntu 20.04 focal main component...
2024/02/29 10:18:59 Fetching index for ubuntu 20.04 focal universe component...
2024/02/29 10:18:59 Fetching ubuntu 20.04 focal-security suite details...
2024/02/29 10:18:59 Release date: Thu, 29 Feb 2024 12:12:56 UTC
2024/02/29 10:18:59 Fetching index for ubuntu 20.04 focal-security main component...
2024/02/29 10:18:59 Fetching …
```
=> feat(20.04): add slice for libc-bin

.github/workflows/ci.yaml, chisel.yaml, slices/base-files.yaml, slices/base-passwd.yaml, slices/bash.yaml, slices/ca-certificates.yaml, slices/dotnet-hostfxr-6.0.yaml, slices/findutils.yaml, slices/iproute2.yaml, slices/libc6.yaml, slices/libcap2.yaml, slices/libpsl5.yaml, slices/libpython3.11-stdlib.yaml, slices/libunwind-13.yaml, slices/libunwind8.yaml, slices/nginx-common.yaml, slices/openssl.yaml, slices/python3.11.yaml, slices/tzdata.yaml
This PR adds a "Lint" job to lint the slices and chisel.yaml.
* #147
* #177
=> chore(23.10): add lint job

slices/libc-bin.yaml
feat(22.04): add slice for libc-bin_locale
#183
#185
```bash
$ chisel cut --release chisel-releases/ --root foo libc-bin_locale
2024/03/07 10:43:31 Processing chisel-releases/ release...
2024/03/07 10:43:31 Selecting slices...
2024/03/07 10:43:31 Fetching ubuntu 22.04 jammy suite details...
2024/03/07 10:43:32 Release date: Thu, 21 Apr 2022 17:16:08 UTC
2024/03/07 10:43:32 Fetching index for ubuntu 22.04 jammy main component...
2024/03/07 10:43:32 Fetching index for ubuntu 22.04 jammy universe component...
2024/03/07 10:43:32 Fetching ubuntu 22.04 jammy-security suite details...
2024/03/07 10:43:32 Release date: Thu, 07 Mar 2024 14:47:11 UTC
2024/03/07 10:43:32 Fetching index for ubuntu 22.04 jammy-security main component...
2024/03/07 10:43:32 Fetching index for ubuntu 22.04 …
```
=> feat(22.04): add slice for libc-bin_locale

slices/libc-bin.yaml
feat(20.04): add slice for libc-bin_locale
#183
#184
```bash
$ chisel cut --release chisel-releases/ --root foo libc-bin_locale
2024/03/07 10:46:52 Processing chisel-releases/ release...
2024/03/07 10:46:53 Selecting slices...
2024/03/07 10:46:53 Fetching ubuntu 20.04 focal suite details...
2024/03/07 10:46:53 Release date: Thu, 23 Apr 2020 17:33:17 UTC
2024/03/07 10:46:53 Fetching index for ubuntu 20.04 focal main component...
2024/03/07 10:46:53 Fetching index for ubuntu 20.04 focal universe component...
2024/03/07 10:46:53 Fetching ubuntu 20.04 focal-security suite details...
2024/03/07 10:46:53 Release date: Wed, 06 Mar 2024 17:08:11 UTC
2024/03/07 10:46:53 Fetching index for ubuntu 20.04 focal-security main component...
2024/03/07 10:46:54 Fetching index for ubuntu 20.04 …
```
=> feat(20.04): add slice for libc-bin_locale

chisel.yaml
Same as https://github.com/canonical/chisel-releases/pull/193.
https://github.com/canonical/chisel-releases/pull/193
=> feat(23.10): bump format to v1

chisel.yaml
=> feat(20.04): bump format to v1

chisel.yaml
Same as https://github.com/canonical/chisel-releases/pull/194
https://github.com/canonical/chisel-releases/pull/194
https://github.com/canonical/chisel-releases/pull/193
=> feat(22.04): bump format to v1

slices/hello.yaml
Add hello slice for ubuntu-24.04.
https://github.com/canonical/chisel-releases/pull/22
=> feat(24.04): add hello slice

slices/p11-kit-modules.yaml, slices/p11-kit.yaml
Add [p11-kit](https://packages.ubuntu.com/jammy/p11-kit) and [p11-kit-modules](https://packages.ubuntu.com/jammy/p11-kit-modules) slices.
#190 
#191 
```bash
rm -rf fs && mkdir -p fs && ~/go/bin/chisel cut --root=$(readlink -f fs) --release=$(readlink -f .) p11-kit_bins && sudo chroot fs /usr/bin/p11-kit list-modules
```
Example output:
```bash
2024/03/12 11:17:20 Processing /home/lwnexgen/Local-Development/chisel-releases release...
2024/03/12 11:17:21 Selecting slices...
2024/03/12 11:17:21 Fetching ubuntu 22.04 jammy suite details...
2024/03/12 11:17:21 Release date: Thu, 21 Apr 2022 17:16:08 UTC
2024/03/12 11:17:21 Fetching index for ubuntu 22.04 jammy main component...
2024/03/12 11:17:21 Fetching index for ubuntu 22.04 jammy universe component...
2024/03/12 11:17:21 Fetching ubuntu …
```
=> feat(22.04): Add p11-kit and p11-kit-modules slices

slices/netbase.yaml
feat(20.04): add slice for netbase
#155
45ae94a2661fe919f5598b1a26bbfa10b684c274
```bash
$ chisel cut --release chisel-releases/ --root foo netbase_default-hosts netbase_default-networks
2024/02/29 10:33:33 Processing chisel-releases/ release...
2024/02/29 10:33:33 Selecting slices...
2024/02/29 10:33:33 Fetching ubuntu 20.04 focal suite details...
2024/02/29 10:33:34 Release date: Thu, 23 Apr 2020 17:33:17 UTC
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal main component...
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal universe component...
2024/02/29 10:33:34 Fetching ubuntu 20.04 focal-security suite details...
2024/02/29 10:33:34 Release date: Thu, 29 Feb 2024 15:57:57 UTC
2024/02/29 10:33:34 Fetching index for ubuntu 20.04 focal-security main component... …
```
=> feat(20.04): add slice for netbase

slices/netbase.yaml
feat(22.04): add slice for netbase
#155
45ae94a2661fe919f5598b1a26bbfa10b684c274
```bash
$ chisel cut --release chisel-releases/ --root foo netbase_default-hosts netbase_default-networks
2024/02/29 10:31:17 Processing chisel-releases/ release...
2024/02/29 10:31:18 Selecting slices...
2024/02/29 10:31:18 Fetching ubuntu 22.04 jammy suite details...
2024/02/29 10:31:18 Release date: Thu, 21 Apr 2022 17:16:08 UTC
2024/02/29 10:31:18 Fetching index for ubuntu 22.04 jammy main component...
2024/02/29 10:31:18 Fetching index for ubuntu 22.04 jammy universe component...
2024/02/29 10:31:18 Fetching ubuntu 22.04 jammy-security suite details...
2024/02/29 10:31:19 Release date: Thu, 29 Feb 2024 15:55:42 UTC
2024/02/29 10:31:19 Fetching index for ubuntu 22.04 jammy-security main component... …
```
=> feat(22.04): add slice for netbase

slices/gcc-14-base.yaml, slices/libgomp1.yaml
Added libgomp1 library to slices in Ubuntu 24.04.
libgomp1 is OpenMP library
Test results, inside ubuntu-24.04 vanilla image docker:
```
apt-get update && apt-get -y install golang-go  ca-certificates
go install github.com/canonical/chisel/cmd/chisel@latest
mkdir -p /test
/root/go/bin/chisel cut --release ./ --root /test libgomp1_libs
024/05/13 07:00:34 Processing ./ release...
2024/05/13 07:00:34 Selecting slices...
2024/05/13 07:00:34 Fetching ubuntu 24.04 noble suite details...
2024/05/13 07:00:35 Release date: Thu, 25 Apr 2024 15:10:33 UTC
2024/05/13 07:00:35 Fetching index for ubuntu 24.04 noble main component...
2024/05/13 07:00:36 Fetching index for ubuntu 24.04 noble universe component...
2024/05/13 07:00:38 Fetching ubuntu 24.04 noble-security suite details...
2024/05/13 07:00:38 …
```
=> feat: add libgomp1 to ubuntu-24.04 release

slices/jq.yaml, slices/libjq1.yaml, slices/libonig5.yaml
=> feat: add jq slices

slices/libyaml-0-2.yaml
Add libyaml-0-2 slice
```bash
./chisel cut --release ./  --root rootfs  --arch=amd64 libyaml-0-2_libs
2024/06/24 15:34:54 Processing ./ release...
2024/06/24 15:34:54 Selecting slices...
2024/06/24 15:34:54 Fetching ubuntu 24.04 noble suite details...
2024/06/24 15:34:55 Release date: Thu, 25 Apr 2024 15:10:33 UTC
2024/06/24 15:34:55 Fetching index for ubuntu 24.04 noble main component...
2024/06/24 15:34:55 Fetching index for ubuntu 24.04 noble universe component...
2024/06/24 15:34:55 Fetching ubuntu 24.04 noble-security suite details...
2024/06/24 15:34:55 Release date: Mon, 24 Jun 2024 11:09:13 UTC
2024/06/24 15:34:55 Fetching index for ubuntu 24.04 noble-security main component...
2024/06/24 15:34:55 Fetching index for ubuntu 24.04 noble-security universe component...
2024/06/24 …
```
=> feat(24.04): add libyaml-0-2 slice

slices/openssl.yaml
Refer to #262 
* #257 
* ROCKS-994
Not applicable. Releases starting from noble already have this.
=> feat(22.04): add 'data' slice to openssl SDF

slices/httping.yaml, slices/libfftw3-double3.yaml
This PR adds the `httping` slice to Ubuntu 22.04, a ping-like program for HTTP requests.
#278 
#279
#278 
#279
```bash
fs=testfs
rm -rf ./$fs; mkdir ./$fs
chisel cut --release ./chisel-releases/ --root $fs httping_bins
sudo chroot $fs /usr/bin/httping --version
2024/07/05 17:08:35 Processing ./chisel-releases/ release...
2024/07/05 17:08:37 Selecting slices...
2024/07/05 17:08:37 Fetching ubuntu 22.04 jammy suite details...
2024/07/05 17:08:39 Release date: Thu, 21 Apr 2022 17:16:08 UTC
2024/07/05 17:08:39 Fetching index for ubuntu 22.04 jammy main component...
2024/07/05 17:08:39 Fetching index for ubuntu 22.04 jammy universe component...
2024/07/05 17:08:39 Fetching ubuntu 22.04 jammy-security suite details...
2024/07/05 17:08:39 Release date: Fri, 05 Jul 2024 22:25:46 UTC
2024/07/05 …
```
=> feat(22.04): add httping slices

.github/workflows/ci.yaml, README.md, slices/libpython3.8-stdlib.yaml, spread.yaml, tests/spread/integration/base-passwd/task.yaml, tests/spread/integration/python3.8/task.yaml, tests/spread/integration/python3.8/test_core.py, tests/spread/integration/python3.8/test_standard.py, tests/spread/lib/install-slices
This is a backport of https://github.com/canonical/chisel-releases/pull/281
#281 
```bash
spread
```
=> ci(spread): support slice testing through Spread (focal)

slices/gcc-11-base.yaml, slices/libasan6.yaml, slices/libasan8.yaml, tests/spread/integration/libasan6/task.yaml, tests/spread/integration/libasan8/task.yaml
Add libasan6 and libasan8 slices.
=> feat(24.04): add libasan6 and libasan8

spread.yaml, tests/spread/integration/openssl/task.yaml
=> test(20.04): add LXD backend to Spread

slices/distro-info-data.yaml
This is a purely data only package, so I haven't added a spread test for this as I'm not sure it'd add any value. But feel free to request one if you think it makes sense.
Can be proposed for 24.10 if approved
=> feat(24.04): add distro-info-data

slices/fonts-ubuntu.yaml, tests/spread/integration/fonts-ubuntu/task.yaml
Add the package fonts-ubuntu, and a very basic test that just ensure slices install
=> feat(24.04): add fonts-ubuntu

spread.yaml
https://github.com/canonical/chisel-releases/pull/365
=> fix(spread): check chisel binary integrity

slices/openjdk-8-jre-headless.yaml
Extract _server and _client slices of the jvm library
https://github.com/canonical/chisel-releases/issues/152
=> feat(24.04): openjdk-8 extract _server_vm and _client_vm slices

spread.yaml, tests/spread/integration/dash/task.yaml
This is a backport of https://github.com/canonical/chisel-releases/pull/369 to Focal
- #369 
- #370
- #371 
=> fix(spread-20.04): make spread work on armhf

slices/libmpeg2-4.yaml, slices/libvpx7.yaml, slices/libx264-163.yaml, slices/libx265-199.yaml
=> feat: add slices for various media encoding libs

slices/librdkafka++1.yaml, slices/librdkafka1.yaml
Add SDF for the `librdkafka++1` package and dependencies
* 24.10 PR: #398
=> feat(24.04): Add SDF for `librdkafka++1`

slices/sbsigntool.yaml
Fix https://github.com/canonical/chisel-releases/actions/runs/12060324342/job/33630542601
=> fix(sbsigntool): missing top-level essential

slices/python3.10-venv.yaml, slices/python3.11-venv.yaml
=> fix: add missing copyrights for python3*venv

slices/xfonts-encodings.yaml
=> fix: typo in essential name

.github/workflows/install-slices.yaml, .github/workflows/lint.yaml
=> ci: add 24.10 to the test matrix

slices/libncursesw6.yaml
libncursesw6 slice, fix copyright
#413 
n/a
=> fix(20.04): libncursesw6 slice, fix copyright

slices/libncursesw6.yaml
libncursesw6 slice, fix copyright
#413 
n/a
=> fix(24.10): libncursesw6 slice, fix copyright

slices/nginx-common.yaml, slices/nginx.yaml, tests/spread/integration/nginx/task.yaml
feat(24.04): forward port slices for NGINX
#59
#422
```shell
$ chisel cut --release chisel-releases/ --root foo base-files_var base-passwd_data nginx_bins
2024/12/06 08:45:26 Processing chisel-releases/ release...
2024/12/06 08:45:39 Selecting slices...
2024/12/06 08:45:39 Fetching ubuntu 24.04 noble suite details...
2024/12/06 08:45:39 Release date: Thu, 25 Apr 2024 15:10:33 UTC
2024/12/06 08:45:39 Fetching index for ubuntu 24.04 noble main component...
2024/12/06 08:45:39 Fetching index for ubuntu 24.04 noble universe component...
2024/12/06 08:45:39 Fetching ubuntu 24.04 noble-security suite details...
2024/12/06 08:45:40 Release date: Fri, 06 Dec 2024 11:22:25 UTC …
```
=> feat(24.04): forward port slices for NGINX

slices/nginx-common.yaml, slices/nginx.yaml, tests/spread/integration/nginx/task.yaml
feat(24.10): forward port slices for NGINX
#59
#421
```shell
$ chisel cut --release chisel-releases/ --root foo base-files_var base-passwd_data nginx_bins
2024/12/06 10:40:06 Processing chisel-releases/ release...
2024/12/06 10:40:08 Selecting slices...
2024/12/06 10:40:08 Fetching ubuntu 24.10 oracular suite details...
2024/12/06 10:40:08 Release date: Fri, 11 Oct 2024 10:20:59 UTC
2024/12/06 10:40:08 Fetching index for ubuntu 24.10 oracular main component...
2024/12/06 10:40:09 Fetching index for ubuntu 24.10 oracular universe component...
2024/12/06 10:40:10 Fetching ubuntu 24.10 oracular-security suite details...
2024/12/06 10:40:10 Release date: Fri, 06 Dec 2024 …
```
=> feat(24.10): forward port slices for NGINX

slices/libatomic1.yaml, slices/libtbb2.yaml
=> feat(20.04): add slices file for package libtbb2 and missing dependencies

slices/git.yaml, slices/libcurl3t64-gnutls.yaml, slices/python3-pyftpdlib.yaml, tests/spread/integration/git/task.yaml, tests/spread/integration/python3-pyftpdlib/task.yaml
Features included in this PR:
- Port forward of git and dependencies from #282 (ubuntu-24.04)
=> Port Forward Git and Dependencies

slices/libhwloc15.yaml, slices/libtbb12.yaml, slices/libtbbbind-2-5.yaml, slices/libtbbmalloc2.yaml
=> feat(24.10): add slices file for package libtbb12 and missing dependencies

slices/libjemalloc2.yaml, slices/liblzf1.yaml, slices/redis-server.yaml, slices/redis-tools.yaml, tests/spread/integration/redis-server/task.yaml, tests/spread/integration/redis-tools/task.yaml
feat(24.10): add slices for Redis and dependencies
#426
```shell
$ chisel cut --release chisel-releases/ --root foo redis-server_bins
2024/12/07 09:04:55 Processing chisel-releases/ release...
2024/12/07 09:04:56 Selecting slices...
2024/12/07 09:04:56 Fetching ubuntu 24.10 oracular suite details...
2024/12/07 09:04:56 Release date: Fri, 11 Oct 2024 10:20:59 UTC
2024/12/07 09:04:56 Fetching index for ubuntu 24.10 oracular main component...
2024/12/07 09:04:56 Fetching index for ubuntu 24.10 oracular universe component...
2024/12/07 09:04:56 Fetching ubuntu 24.10 oracular-security suite details...
2024/12/07 09:04:56 Release date: Sat, 07 Dec 2024 11:18:07 UTC
2024/12/07 …
```
=> feat(24.10): add slices for Redis and dependencies

slices/gosu.yaml, tests/spread/integration/gosu/task.yaml
feat(24.10): add slice for gosu
#430
```shell
$ chisel cut --release chisel-releases/ --root foo gosu_bins
2024/12/12 07:25:59 Processing chisel-releases/ release...
2024/12/12 07:26:00 Selecting slices...
2024/12/12 07:26:00 Fetching ubuntu 24.10 oracular suite details...
2024/12/12 07:26:01 Release date: Fri, 11 Oct 2024 10:20:59 UTC
2024/12/12 07:26:01 Fetching index for ubuntu 24.10 oracular main component...
2024/12/12 07:26:01 Fetching index for ubuntu 24.10 oracular universe component...
2024/12/12 07:26:01 Fetching ubuntu 24.10 oracular-security suite details...
2024/12/12 07:26:01 Release date: Thu, 12 Dec 2024  8:18:40 UTC
2024/12/12 07:26:01 Fetching index …
```
=> feat(24.10): add slice for gosu

slices/gosu.yaml, tests/spread/integration/gosu/task.yaml
feat(24.04): add slice for gosu
#431
```shell
$ chisel cut --release chisel-releases/ --root foo gosu_bins
2024/12/12 07:19:49 Processing chisel-releases/ release...
2024/12/12 07:20:03 Selecting slices...
2024/12/12 07:20:03 Fetching ubuntu 24.04 noble suite details...
2024/12/12 07:20:04 Release date: Thu, 25 Apr 2024 15:10:33 UTC
2024/12/12 07:20:04 Fetching index for ubuntu 24.04 noble main component...
2024/12/12 07:20:04 Fetching index for ubuntu 24.04 noble universe component...
2024/12/12 07:20:04 Fetching ubuntu 24.04 noble-security suite details...
2024/12/12 07:20:04 Release date: Thu, 12 Dec 2024 10:46:25 UTC
2024/12/12 07:20:04 Fetching index for ubuntu …
```
=> feat(24.04): add slice for gosu

slices/ocl-icd-libopencl1.yaml
Port #353 to the 24.10 branch
#391
=> feat(24.10): add SDF for `ocl-icd-libopencl1`

slices/libcdio-cdda2t64.yaml, slices/libcdio-paranoia2t64.yaml, slices/libcdio19t64.yaml, slices/libnorm1t64.yaml, slices/libpgm-5.3-0t64.yaml, slices/libxcb-dri2-0.yaml, slices/libxcb-dri3-0.yaml, slices/libxcb-glx0.yaml, slices/libxcb-present0.yaml, slices/libxcb-randr0.yaml, slices/libxcb-shape0.yaml, slices/libxcb-sync1.yaml, slices/libxcb-xfixes0.yaml, slices/libzimg2.yaml, slices/libzmq5.yaml
Port #328 for  the 24.10 branch
#391
=> feat(24.10): add ffmpeg dependencies slices

slices/bc.yaml, tests/spread/integration/bc/task.yaml
feat(24.04): add SDF for bc
#446 
=> feat(24.04): add SDF for bc

slices/bc.yaml, tests/spread/integration/bc/task.yaml
feat(24.10): add SDF for bc
#445 
=> feat(24.10): add SDF for bc

slices/mawk.yaml, tests/spread/integration/mawk/task.yaml
feat(24.04): add SDF for Mawk
#452 
=> feat(24.04): add SDF for Mawk

slices/mawk.yaml, tests/spread/integration/mawk/task.yaml
feat(24.10): add SDF for Mawk
#451 
=> feat(24.10): add SDF for Mawk

slices/iputils-ping.yaml, tests/spread/integration/iputils-ping/task.yaml
feat(24.10): add slices for iputils-ping
#449 
=> feat(24.10): add slices for iputils-ping

slices/cpio.yaml, tests/spread/integration/cpio/task.yaml
feat(24.10): add SDF for cpio
#447 
=> feat(24.10): add SDF for cpio

slices/gearman-job-server.yaml, slices/gearman-tools.yaml, slices/libboost-program-options1.83.0.yaml, slices/libevent-2.1-7t64.yaml, slices/libevent-core-2.1-7t64.yaml, slices/libevent-pthreads-2.1-7t64.yaml, slices/libgearman8t64.yaml, slices/libhashkit2t64.yaml, slices/libhiredis1.1.0.yaml, slices/libmemcached11t64.yaml, slices/libmysqlclient21.yaml, slices/mysql-common.yaml, tests/spread/integration/gearman-job-server/task.yaml, tests/spread/integration/gearman-tools/task.yaml
feat(24.10): add slices for Gearman and dependencies
#443 
=> feat(24.10): add slices for Gearman and dependencies

slices/libarchive-tools.yaml, slices/libarchive13t64.yaml, tests/spread/integration/libarchive-tools/task.yaml
feat(24.10): add SDF for libarchive-tools and dependencies
#455 
=> feat(24.10): add SDF for libarchive-tools and dependencies

slices/libxml2-utils.yaml, tests/spread/integration/libxml2-utils/task.yaml
feat(24.04): add SDF for libxml2-utils
=> feat(24.04): add SDF for libxml2-utils

slices/sqlite3.yaml, tests/spread/integration/sqlite3/task.yaml
feat(24.10): add SDF for sqlite3
#463
=> feat(24.10): add SDF for sqlite3

slices/sqlite3.yaml, tests/spread/integration/sqlite3/task.yaml
feat(24.04): add SDF for sqlite3
#464 
=> feat(24.04): add SDF for sqlite3

slices/bind9-dnsutils.yaml, slices/bind9-host.yaml, slices/bind9-libs.yaml, slices/liblmdb0.yaml, tests/spread/integration/bind9-dnsutils/task.yaml, tests/spread/integration/bind9-host/task.yaml
feat(24.04): add SDF for bind9-dnsutils, bind9-host and dependencies
#458 
=> feat(24.04): add SDF for bind9-dnsutils, bind9-host and dependencies

slices/bind9-dnsutils.yaml, slices/bind9-host.yaml, slices/bind9-libs.yaml, slices/liblmdb0.yaml, slices/liburcu8t64.yaml, tests/spread/integration/bind9-dnsutils/task.yaml, tests/spread/integration/bind9-host/task.yaml
feat(24.10): add SDF for bind9-dnsutils, bind9-host and dependencies
#457 
=> feat(24.10): add SDF for bind9-dnsutils, bind9-host and dependencies

slices/pwgen.yaml, tests/spread/integration/pwgen/task.yaml
feat(24.04): add SDF for pwgen
#476 
=> feat(24.04): add SDF for pwgen

slices/pwgen.yaml, tests/spread/integration/pwgen/task.yaml
feat(24.10): add SDF for pwgen
#467 
=> feat(24.10): add SDF for pwgen

README.md
Updated README to point to the docs website.
=> Update links to the docs

slices/patch.yaml, tests/spread/integration/patch/task.yaml
feat(24.04): add SDF for patch
#481 
=> feat(24.04): add SDF for patch

slices/unzip.yaml, slices/zip.yaml, tests/spread/integration/unzip/task.yaml, tests/spread/integration/zip/task.yaml
feat(24.04): add SDF for zip and unzip
#479 
=> feat(24.04): add SDF for zip and unzip

slices/netcat-openbsd.yaml, tests/spread/integration/netcat-openbsd/task.yaml
feat(24.04): add SDF for netcat-openbsd
#489 
=> feat(24.04): add SDF for netcat-openbsd

slices/netcat-openbsd.yaml, tests/spread/integration/netcat-openbsd/task.yaml
feat(24.10): add SDF for netcat-openbsd
#488 
=> feat(24.10): add SDF for netcat-openbsd

slices/libpam-runtime.yaml, slices/sudo.yaml, slices/util-linux.yaml, tests/spread/integration/libpam-runtime/task.yaml, tests/spread/integration/sudo/task.yaml, tests/spread/integration/util-linux/task.yaml
Forward port the changes related to `util-linux` from 24.04.
#306 
#330 
Not Applicable.
=> feat(24.10): forward port util-linux and deps

slices/bzip2.yaml, tests/spread/integration/bzip2/task.yaml
From https://github.com/canonical/chisel-releases/pull/337
Needs #493
=> feat(24.10): forward port bzip2

slices/tar.yaml, tests/spread/integration/tar/task.yaml
This PR back ports the suggested changes from #492; adding tarcat tests and refining the tar slice. See comment :https://github.com/canonical/chisel-releases/pull/492#issuecomment-2689038648
=> feat: backport tar suggestions from oracular

slices/libswscale7.yaml
Add SDF for `libswscale7`
24.10 PR: #519
=> feat(24.04): Add SDF for `libswscale7`

slices/libswscale8.yaml
Add SDF for `libswscale8`
24.04 PR: #520
=> feat(24.10): Add SDF for `libswscale8`

slices/liblua5.4-0.yaml, slices/lua5.4.yaml, tests/spread/integration/liblua5.4-0/task.yaml, tests/spread/integration/lua5.4/task.yaml
Add slices for:
- lua5.4
- liblua5.4-0
=> feat(24.04): add lua5.4 slices

README.md
- updates to the readme for 25.04
=> fix(25.04): update readme

slices/conmon.yaml, tests/spread/integration/conmon/task.yaml
Por forward for conmon slice.
This is part of issue #544 
=> feat(24.10): add conmon slice

.github/workflows/ci.yaml
=> ci(24.10): check for removed slices

.github/workflows/ci.yaml
=> ci(24.04): check for removed slices

slices/debianutils.yaml, slices/gzip.yaml, slices/util-linux.yaml, tests/spread/integration/debianutils/task.yaml, tests/spread/integration/gzip/task.yaml
This PR adds the utilities gzip and debianutils (mainly for `which`)
N/A
N/A. Will be ported to 24.04 once approved.
The `gzip` slice definition references the implementation from #331
=> feat(25.04): add gzip and debianutils

.github/workflows/install-slices.yaml, README.md
Set the CI and README for opening `ubuntu-25.10`
=> feat(25.10): open ubuntu-25.10 release

slices/libc6-dev.yaml, slices/libcrypt-dev.yaml, slices/linux-libc-dev.yaml
This PR is the forward port of #633.
Minor changes from 25.04. dpkg listing data available [here](https://github.com/lczyk/deb-data-dump)
#633 
n/a
=> feat(25.10): libc6-dev slices

.github/scripts/install-slices/install_slices.py, .github/workflows/install-slices.yaml
=> ci: ignore unstable chisel releases

slices/libc-bin.yaml, tests/spread/integration/libc-bin/task.yaml
This PR adds the `locale` binary in `libc-bin`.
N/A
#689 
#690 
N/A
=> feat(24.04): add locale binary

slices/libc-bin.yaml, tests/spread/integration/libc-bin/task.yaml
This PR adds the `locale` binary in `libc-bin`.
N/A
#690 
N/A
=> feat(25.04): add locale binary

slices/apparmor.yaml
Update the contents of `/etc/apparmor.d/` for 25.10.
Supersedes #642
n/a
=> feat(25.10): update new/missing files in apparmor for 25.10

.github/scripts/install-slices/install_slices.py, .github/workflows/install-slices.yaml
=> fix: pass chisel version to install_slices.py

slices/dpkg.yaml, slices/libgdk-pixbuf-2.0-0.yaml, slices/libpython3.13-stdlib.yaml, slices/openssh-server.yaml, slices/openssh-sftp-server.yaml, slices/tar.yaml, slices/vim-common.yaml
=> feat(25.10): missing copyright + nitpicks

slices/libc-bin.yaml, tests/spread/integration/libc-bin/task.yaml
This PR adds the `locale` binary in `libc-bin`.
N/A
N/A
N/A
=> feat(25.10): add locale binary

slices/sudo.yaml
Updated filenames and added appropriate symlinks based on the `postinst`
unblocks:
- https://github.com/canonical/chisel-releases/pull/673
resolves:
- https://github.com/canonical/chisel-releases/issues/658
n/a
=> feat(25.10): update sudo for 25.10

slices/procps.yaml
Update the location of the config files
unblocks:
- https://github.com/canonical/chisel-releases/pull/673
n/a
=> feat(25.10): update procps for 25.10

slices/base-files.yaml
Forward port of  https://github.com/canonical/chisel-releases/pull/685
https://github.com/canonical/chisel-releases/pull/685
=> fix(25.04): base-files_etc - add /etc/profile.d
